import type { ToolCategory } from "./types";

type CategoryContent = {
  overview: string[];
  analysisTitle: string;
  analysis: string[];
  applications: Array<{ title: string; text: string }>;
  checklist: string[];
  faqs: Array<{ question: string; answer: string }>;
};

export const categoryContent: Record<ToolCategory, CategoryContent> = {
  "electrical-fundamentals": {
    overview: ["Electrical fundamentals connect voltage, current, resistance, power, energy, time, and power factor. These quantities are the starting point for nearly every downstream cable, breaker, motor, transformer, battery, and control-panel decision.", "The calculators in this category keep units and system type visible so a DC relationship is not accidentally mixed with single-phase or balanced three-phase assumptions."],
    analysisTitle: "From a known value to an engineering input",
    analysis: ["The most useful calculator is the narrowest one that matches the question. Ohm's law suits V-I-R relationships, power calculators distinguish kW from kVA, and circuit tools address divider ratios or passive networks.", "A mathematically correct result is not automatically an equipment rating. Treat it as a transparent intermediate value, then continue to the relevant protection, conductor, thermal, or product-selection check."],
    applications: [{ title: "Load conversion", text: "Translate nameplate power, voltage, efficiency, and power factor into operating current." }, { title: "Circuit analysis", text: "Review resistor networks, voltage division, impedance, energy, and time relationships." }, { title: "Input verification", text: "Cross-check measured or specified quantities before equipment sizing begins." }],
    checklist: ["Choose DC, single-phase, or three-phase correctly.", "Keep RMS, peak, line, and phase values distinct.", "Convert prefixes such as m, k, and M before comparing results.", "Apply efficiency and power factor only where the equation requires them."],
    faqs: [{ question: "Which electrical calculator should I start with?", answer: "Start with the quantity you need to find and the values you already know. Use Ohm's law for voltage, current, and resistance; a power calculator for watts, VA, or power factor; and a dedicated circuit calculator for networks or time-dependent behavior." }, { question: "Why do AC results differ from DC results?", answer: "AC calculations may require RMS values, phase arrangement, power factor, and impedance. DC calculations generally use steady voltage and current without a phase factor." }, { question: "Can a formula result select a breaker or cable directly?", answer: "No. The calculated current becomes an input to breaker, cable, voltage-drop, fault, and installation checks." }]
  },
  "cable-wire": {
    overview: ["Cable and wire selection must satisfy current-carrying capacity, voltage drop, installation derating, terminal limits, and short-circuit thermal withstand. Conductor material and cross-sectional area alone do not complete the selection.", "These tools separate conductor electrical performance from the physical routing and termination questions covered under Cable Management & Installation."],
    analysisTitle: "Ampacity, voltage drop, and fault duty are separate checks",
    analysis: ["A conductor can pass ampacity but fail voltage drop on a long run, or pass normal operation but fail the adiabatic short-circuit check. Each condition should be calculated on the same load, route, material, and protection basis.", "AWG and mm² are different nominal systems. A nearest conversion is useful for comparison, but final selection should use an available standard size that is not smaller than the required electrical area."],
    applications: [{ title: "Feeder and branch circuits", text: "Estimate conductor size from load, phase, installation method, and allowable voltage drop." }, { title: "DC and low-voltage systems", text: "Control voltage loss in battery, PV accessory, LED, control, and automotive-style circuits." }, { title: "Fault withstand", text: "Compare conductor area with fault current and protective-device clearing time." }],
    checklist: ["Use one-way route length with the equation's stated path factor.", "Apply ambient, grouping, soil, and installation factors from the adopted standard.", "Check terminal temperature ratings and parallel-conductor rules.", "Verify both operating voltage drop and short-circuit withstand."],
    faqs: [{ question: "Is cable size determined by current only?", answer: "No. Ampacity is only one requirement. Voltage drop, fault withstand, installation method, ambient temperature, grouping, terminals, and mechanical minimums can require a larger conductor." }, { question: "Can cable outside diameter be converted to mm²?", answer: "No. Outside diameter includes insulation, fillers, screens, armor, and sheath. Conductor cross-sectional area must come from the cable construction or datasheet." }, { question: "Should I choose the nearest AWG equivalent?", answer: "Use nearest AWG for reference. For capacity selection, use a standard conductor whose verified area and ampacity meet or exceed the requirement." }]
  },
  "cable-management": {
    overview: ["Cable management begins after the conductor and cable construction are known. Raceway fill, tray occupancy, pulling limits, gland clamping range, thread system, lug barrel, and stud size determine whether the selected cable can be installed and terminated correctly.", "Physical cable outside diameter is the governing input for many installation calculations; conductor mm² or AWG alone cannot predict the finished cable diameter."],
    analysisTitle: "Design the complete cable path, not one fitting",
    analysis: ["A valid route must accommodate cable quantity, bend radius, pulling tension, heat dissipation, entry sealing, mechanical retention, and termination access. Changing cable construction can affect every downstream installation component.", "Gland and lug selection remains manufacturer-specific. Calculator results should narrow the family and size range before the exact product clamping table, material, certification, and installation instructions are checked."],
    applications: [{ title: "Raceway and tray planning", text: "Screen conduit or tray occupancy and available routing space before installation." }, { title: "Enclosure entries", text: "Match cable OD, armor, environment, and thread system to a gland family." }, { title: "Conductor termination", text: "Match conductor area, material, palm, hole, and crimp system to a cable lug." }],
    checklist: ["Use finished cable OD from the exact datasheet.", "Apply the fill rule for the adopted code and cable type.", "Confirm bend radius, pulling tension, and sidewall pressure.", "Maintain the enclosure rating at every entry and unused opening."],
    faqs: [{ question: "Can I select a cable gland from conductor mm² alone?", answer: "Only as a preliminary reference. The final gland is selected by finished cable OD, cable construction, armor, sealing duty, thread, material, and certification." }, { question: "Why do conduit and tray fill rules differ?", answer: "They address different pathway constructions, heat conditions, cable arrangements, and code requirements. Use the rule applicable to the actual pathway and cable type." }, { question: "Does a correct lug size guarantee a valid termination?", answer: "No. The conductor class, material, barrel geometry, plating, stud hole, crimp tooling, die, and terminal instructions must all be compatible." }]
  },
  "circuit-protection": {
    overview: ["Circuit protection coordinates load current, conductor capacity, overload response, instantaneous or magnetic operation, prospective fault current, breaking capacity, earth-fault path, and disconnection time.", "Breakers, fuses, RCDs, RCBOs, and grounding conductors perform different functions. A complete design often requires several protection devices working together."],
    analysisTitle: "Protection is a coordinated system",
    analysis: ["A device rating above load current is not enough. Its trip behavior must protect the conductor, tolerate legitimate inrush, interrupt the available fault current, and coordinate with upstream and downstream devices.", "Ground-fault and residual-current protection are related but not interchangeable. Loop impedance concerns fault current and automatic disconnection, while RCD or RCBO type and sensitivity concern residual-current waveform and leakage protection."],
    applications: [{ title: "Overcurrent selection", text: "Screen MCB, MCCB, fuse, and motor-protection ratings from the actual load basis." }, { title: "Fault and grounding checks", text: "Estimate available fault current, loop impedance, grounding requirements, and breaking duty." }, { title: "Coordination and safety", text: "Review inrush compatibility, selectivity, cascading, and incident-energy conditions." }],
    checklist: ["Confirm design current, conductor ampacity, and device rating relationship.", "Compare breaking capacity with prospective fault current.", "Use manufacturer trip curves and selectivity tables.", "Verify grounding, bonding, residual-current type, and disconnection requirements."],
    faqs: [{ question: "What is the difference between rated current and breaking capacity?", answer: "Rated current describes continuous carrying duty. Breaking capacity describes the maximum prospective fault current the device can interrupt under specified conditions." }, { question: "Can B, C, and D curves be selected from load current alone?", answer: "No. Curve selection also depends on inrush, fault current at the installation point, conductor protection, and disconnection requirements." }, { question: "Does an RCD replace overcurrent protection?", answer: "Not unless it is an RCBO with integrated overcurrent protection. An RCCB or RCD normally requires coordinated upstream overcurrent protection." }]
  },
  "power-distribution": {
    overview: ["Power-system planning connects source capacity, transformer and generator behavior, maximum demand, transfer switching, busbar duty, power factor, harmonics, and available fault current.", "The objective is to maintain capacity and acceptable voltage across credible operating states, including normal supply, standby supply, starting events, future growth, and faults."],
    analysisTitle: "Define the operating scenario before sizing equipment",
    analysis: ["Connected load, maximum demand, starting load, and emergency load are different quantities. Transformer, generator, ATS, feeder, and busbar sizing should use the scenario that actually governs each item.", "Power quality can change equipment current and thermal stress even when kW demand appears acceptable. Harmonics, unbalance, low power factor, and source impedance should be reviewed where non-linear or motor loads are significant."],
    applications: [{ title: "Source sizing", text: "Screen transformer and generator kVA, loading margin, impedance, and standby capacity." }, { title: "Distribution capacity", text: "Estimate maximum demand, feeder current, ATS duty, busbar loading, and future spare." }, { title: "System performance", text: "Review power factor, fault contribution, voltage regulation, and harmonic exposure." }],
    checklist: ["Separate connected load from coincident maximum demand.", "Include motor starting and largest-step load where relevant.", "Check normal and emergency operating configurations.", "Confirm fault level, protection coordination, power quality, and expansion margin."],
    faqs: [{ question: "Should a transformer be sized from connected load?", answer: "Not automatically. Use justified demand, diversity, future growth, loading policy, ambient derating, harmonic duty, and starting requirements." }, { question: "Why does transformer impedance matter?", answer: "Percent impedance affects voltage regulation and limits secondary short-circuit current, influencing protective-device and busbar duty." }, { question: "Can an ATS be selected by amperes only?", answer: "No. Poles, utilization category, PC or CB class, short-circuit rating, transfer time, source arrangement, neutral treatment, and control requirements also matter." }]
  },
  "panels-enclosures": {
    overview: ["Panel reliability depends on component heat loss, terminal resistance, enclosure surface and airflow, ambient temperature, clearance, creepage, ingress protection, and production tolerances.", "These tools address the conditions inside and at the boundary of the assembled enclosure rather than the upstream distribution-system capacity."],
    analysisTitle: "Electrical, thermal, and mechanical limits interact",
    analysis: ["A panel can pass steady current calculations and still fail because of local hot spots, poor joint resistance, restricted ventilation, high ambient temperature, or inadequate spacing. Thermal and insulation checks should be performed on the actual arrangement.", "NEMA and IEC IP classifications are not reversible equivalents. Cable entries, doors, operators, ventilation components, drains, and unused openings must preserve the required assembled enclosure performance."],
    applications: [{ title: "Thermal design", text: "Estimate internal losses, average temperature rise, airflow, and enclosure cooling needs." }, { title: "Connections and buswork", text: "Review terminal I²R loss, busbar forces, supports, and joint conditions." }, { title: "Insulation and enclosure", text: "Screen clearance, creepage, CTI, altitude, NEMA Type, and IP ingress protection." }],
    checklist: ["Use manufacturer watt-loss data at the expected load.", "Review local hot spots rather than average temperature alone.", "Apply product-standard clearance and creepage requirements.", "Verify the rating of the complete modified enclosure assembly."],
    faqs: [{ question: "Can enclosure temperature be predicted from watts alone?", answer: "No. Temperature rise also depends on enclosure area, material, installation, ambient, airflow, internal layout, and heat-transfer conditions." }, { question: "Is IP66 equivalent to NEMA 4X?", answer: "No. IP addresses ingress characteristics; NEMA Types can include corrosion, icing, oil, construction, and other requirements." }, { question: "Why is terminal resistance important?", answer: "Connection heating follows I²R. Small resistance increases can produce substantial localized heat at high current." }]
  },
  "motor-control": {
    overview: ["Motor circuits must carry normal load, tolerate starting current, provide overload and short-circuit protection, and switch the load at the required duty. Motor current is only the first step.", "Contactor utilization category, starter method, acceleration time, starts per hour, voltage quality, service factor, and VFD derating can govern the final equipment selection."],
    analysisTitle: "Separate running duty from starting duty",
    analysis: ["Full-load current determines continuous current paths, while locked-rotor or controlled starting current affects voltage dip, magnetic trip compatibility, contactor making duty, and source capacity.", "VFD and soft-starter applications require manufacturer data for output current, overload class, carrier frequency, ambient temperature, altitude, cable length, EMC, harmonics, and motor compatibility."],
    applications: [{ title: "Motor operating point", text: "Estimate current, input power, efficiency, torque, and phase behavior." }, { title: "Starting and switching", text: "Compare DOL, star-delta, soft starter, VFD, contactor, and overload requirements." }, { title: "Motor control panels", text: "Screen feeder load, starting voltage drop, voltage unbalance, heat, and protection." }],
    checklist: ["Prefer exact nameplate current over a formula estimate.", "Identify duty, starts per hour, and acceleration time.", "Check utilization category and coordinated protection tables.", "Apply VFD or starter environmental and overload derating."],
    faqs: [{ question: "Why is motor nameplate current preferred?", answer: "It reflects the actual motor design and rating basis. Formula current is useful when nameplate data is unavailable, but efficiency and power factor assumptions introduce uncertainty." }, { question: "Does a VFD remove motor starting-current concerns?", answer: "It reduces line-side starting impact but introduces drive current, overload, harmonic, thermal, EMC, and protection requirements." }, { question: "Can one contactor rating cover every motor application?", answer: "No. AC-1, AC-3, AC-4 and other utilization categories have different making, breaking, and endurance duties." }]
  },
  "solar-storage": {
    overview: ["Solar, battery, inverter, and backup-power calculations must keep voltage window, energy capacity, power capability, charge and discharge rate, efficiency, temperature, and protection separate.", "PV string voltage changes with temperature, while battery capacity and runtime change with discharge rate, state of charge, depth of discharge, age, and environmental conditions."],
    analysisTitle: "Balance energy, power, and operating limits",
    analysis: ["kWh describes stored or consumed energy; kW describes power; and C-rate connects battery current to capacity. A system can have sufficient energy but insufficient peak power, or sufficient power but inadequate runtime.", "PV and battery protection must be selected for DC voltage, polarity, fault behavior, isolation, and manufacturer requirements. AC protective-device assumptions should not be transferred to DC systems without verification."],
    applications: [{ title: "PV array configuration", text: "Screen string count, cold Voc, hot Vmpp, combiner current, inverter range, and DC protection." }, { title: "Battery and UPS sizing", text: "Estimate Ah, kWh, C-rate, usable energy, runtime, charger recovery, and parallel strings." }, { title: "Off-grid and backup planning", text: "Connect daily load, solar resource, autonomy, inverter power, and backup operating scenarios." }],
    checklist: ["Use temperature-corrected PV module voltages.", "Separate nominal battery energy from usable delivered energy.", "Check both continuous and surge power capability.", "Verify BMS, inverter, charger, fuse, breaker, SPD, and isolation ratings."],
    faqs: [{ question: "What is the difference between battery kW and kWh?", answer: "kW is instantaneous power capability; kWh is stored energy. Both must satisfy the load and runtime requirement." }, { question: "Does connecting batteries in series increase Ah?", answer: "No. Series increases voltage. Parallel strings increase Ah and current capability, subject to manufacturer limits and balancing." }, { question: "Why is cold PV open-circuit voltage important?", answer: "Module Voc rises as temperature falls and must remain below the inverter, controller, isolator, and protection maximum DC voltage." }]
  },
  "ev-charging": {
    overview: ["EV charging design links vehicle energy demand with charger power, phase arrangement, charging duration, efficiency, tariff, feeder capacity, simultaneity, and load management.", "Overcurrent, residual-current, surge, cable, voltage-drop, and fault-current checks remain separate decisions and must follow the charger instructions and local EV installation rules."],
    analysisTitle: "Separate the charging session from installation capacity",
    analysis: ["Battery size and target state of charge determine session energy, while charger power and efficiency determine duration. The building sees charger input power, not only energy delivered to the battery.", "Multiple chargers rarely operate from a simple sum without considering simultaneity or active load management. The accepted diversity method must match the project, utility, and local requirements."],
    applications: [{ title: "Driver planning", text: "Estimate charging time, wall energy, and session cost from battery and charger data." }, { title: "Site load planning", text: "Calculate charger current, quantity, simultaneity, and distribution demand." }, { title: "Protection workflow", text: "Continue to cable, breaker, RCBO or RCD, SPD, voltage-drop, and fault-current checks." }],
    checklist: ["Use charger AC input rating and phase arrangement.", "Include charging efficiency and vehicle taper behavior.", "Define simultaneity or load-management strategy.", "Follow charger requirements for RCD type and DC leakage detection."],
    faqs: [{ question: "Why is actual charging time longer than battery kWh divided by charger kW?", answer: "Charging losses, vehicle power limits, temperature conditioning, and high-SOC tapering reduce the average power delivered to the battery." }, { question: "Can all EV chargers be added at 100 percent demand?", answer: "That is conservative but may not reflect an approved load-management design. Use the demand method accepted by the project authority and utility." }, { question: "Does every EV charger require a Type B RCD?", answer: "Not always. The required type depends on charger-integrated DC detection, waveform behavior, manufacturer instructions, and local rules." }]
  },
  "surge-protection": {
    overview: ["Surge protection selection begins with lightning exposure, supply route, installation point, earthing system, nominal voltage, equipment withstand, and coordination between protective stages.", "SPD Type, Uc, Up, In, Imax, Iimp, short-circuit rating, backup protection, connection length, and wiring arrangement must be considered together."],
    analysisTitle: "Select and coordinate the protection stages",
    analysis: ["Type 1 addresses partial lightning current at exposed service origins, Type 2 limits switching and induced surges in distribution, and Type 3 provides local fine protection near sensitive equipment. Combined devices can cover more than one duty when correctly rated.", "A low protective level on paper can be defeated by long connection leads. Installation geometry and bonding are part of SPD performance, not an afterthought."],
    applications: [{ title: "Building and panel protection", text: "Screen SPD type from LPS, supply exposure, installation point, and downstream equipment." }, { title: "PV and DC systems", text: "Check maximum operating voltage, array configuration, polarity, and DC-specific SPD construction." }, { title: "Coordination and backup", text: "Review upstream/downstream SPD stages, distance, backup fuse, and prospective fault current." }],
    checklist: ["Identify the earthing system and maximum continuous voltage.", "Match SPD type to lightning exposure and installation location.", "Coordinate Up with equipment impulse withstand.", "Check lead length, backup protection, fault rating, and status indication."],
    faqs: [{ question: "What is the difference between Type 1 and Type 2 SPD?", answer: "Type 1 is tested for partial lightning-current duty and is commonly used at exposed origins. Type 2 is tested for induced and switching surge duty in distribution systems." }, { question: "Can a lower Up value always be considered better?", answer: "Only when Uc, system compatibility, energy duty, coordination, lead length, and equipment withstand are also satisfied." }, { question: "When is SPD backup protection required?", answer: "Follow the exact SPD datasheet. The requirement and maximum backup rating depend on the SPD design, upstream device, and prospective short-circuit current." }]
  },
  "lighting-design": {
    overview: ["Lighting calculations connect the required maintained illuminance with room area, fixture lumens, utilization, maintenance, mounting, power, controls, and circuit loading.", "A lumen-method estimate is useful for early fixture quantity and electrical load planning, but it cannot prove uniformity, glare control, visual comfort, or emergency-lighting compliance."],
    analysisTitle: "Move from a light-level target to a complete circuit",
    analysis: ["The target lux or footcandles should come from the actual space and task requirement. Fixture efficacy alone does not determine delivered illuminance because room geometry, optical distribution, surface reflectance, utilization, and depreciation affect the result.", "Electrical design must also account for LED driver inrush, power factor, harmonics, dimming and control gear, emergency supply, voltage drop, and switching-device duty."],
    applications: [{ title: "Concept lighting layout", text: "Estimate lumens and fixture count from target illuminance, area, utilization, and maintenance." }, { title: "Lighting circuit planning", text: "Calculate connected watts, current, circuit quantity, voltage drop, and control-device loading." }, { title: "Emergency and efficiency", text: "Screen backup energy, operating duration, LED savings, and maintained-light output." }],
    checklist: ["Choose a maintained illuminance target for the actual task.", "Use fixture lumens and photometric data, not lamp watts alone.", "Check uniformity, glare, mounting height, and spacing separately.", "Review driver inrush, emergency duration, controls, and circuit protection."],
    faqs: [{ question: "What is the difference between lumens and lux?", answer: "Lumens describe light emitted by a source. Lux describes lumens received per square meter on a surface." }, { question: "Can fixture count be calculated from room area alone?", answer: "No. Target illuminance, fixture lumens, utilization factor, maintenance factor, layout, mounting, and photometric distribution are also required." }, { question: "Why can LED lighting trip a breaker below its steady current rating?", answer: "LED drivers can produce high short-duration inrush. Breaker curve, driver quantity, inrush data, switching device, and manufacturer guidance must be checked." }]
  }
};
