import type { ToolEquation, ToolEquationSymbol } from "./types";

const make = (title: string, intro: string, expressions: string[], symbols: ToolEquationSymbol[], conclusion: string): ToolEquation => ({ title, intro, equations: expressions.map((expression) => ({ expression })), symbols, conclusion });

export const expansionEquations: Record<string, ToolEquation> = {
  "ohms-law-calculator": make("Ohm's law equations", "Voltage, current, resistance, and power describe one resistive operating point.", ["V = I × R", "P = V × I = I² × R = V² / R"], [{ symbol: "V", meaning: "Voltage", unit: "V" }, { symbol: "I", meaning: "Current", unit: "A" }, { symbol: "R", meaning: "Resistance", unit: "Ω" }, { symbol: "P", meaning: "Electrical power", unit: "W" }], "These relationships apply directly to DC and ideal resistive loads."),
  "watts-amps-volts-calculator": make("Watts, amps, and volts equations", "The current equation changes with the phase arrangement.", ["DC: P = V × I", "Single-phase: P = V × I × pf", "Three-phase: P = √3 × VLL × I × pf"], [{ symbol: "P", meaning: "Active power", unit: "W" }, { symbol: "V", meaning: "DC or single-phase voltage", unit: "V" }, { symbol: "VLL", meaning: "Three-phase line-to-line voltage", unit: "V" }, { symbol: "I", meaning: "Line current", unit: "A" }, { symbol: "pf", meaning: "Power factor" }], "Use line-to-line voltage for a balanced three-phase load."),
  "ev-charging-time-cost-calculator": make("EV charging time and cost equations", "The battery receives less energy than the supply delivers because charging is not perfectly efficient.", ["Ebatt = C × (SOCtarget − SOCstart)", "Ewall = Ebatt / η", "t = Ewall / Pcharger", "Cost = Ewall × tariff"], [{ symbol: "C", meaning: "Usable battery capacity", unit: "kWh" }, { symbol: "SOC", meaning: "State of charge" }, { symbol: "η", meaning: "Charging efficiency" }, { symbol: "t", meaning: "Charging time", unit: "h" }], "Actual time can be longer when the vehicle tapers charging power."),
  "battery-charging-time-calculator": make("Battery charging time equation", "Required capacity is divided by the effective average charging rate.", ["t = C × ΔSOC / (rate × η)"], [{ symbol: "t", meaning: "Charging time", unit: "h" }, { symbol: "C", meaning: "Battery capacity in Ah or kWh" }, { symbol: "ΔSOC", meaning: "Target minus starting state of charge" }, { symbol: "η", meaning: "Charging efficiency" }], "Use average current or power over the complete charging period."),
  "resistor-series-parallel-calculator": make("Series and parallel resistance equations", "Series resistances add directly; parallel conductances add.", ["Series: Req = R1 + R2 + … + Rn", "Parallel: 1 / Req = 1/R1 + 1/R2 + … + 1/Rn"], [{ symbol: "Req", meaning: "Equivalent resistance", unit: "Ω" }, { symbol: "Rn", meaning: "Individual resistor value", unit: "Ω" }], "Power and voltage ratings must be checked for every individual resistor."),
  "electrical-unit-converter": make("Electrical unit conversion method", "Power values are converted through watts and energy values through joules.", ["Pto = Pfrom × Kfrom / Kto", "Eto = Efrom × Kfrom / Kto"], [{ symbol: "K", meaning: "Unit-to-base conversion factor" }, { symbol: "P", meaning: "Power" }, { symbol: "E", meaning: "Energy" }], "Power cannot be converted to energy without adding a duration."),
  "contactor-selection-calculator": make("Contactor load-current equation", "Three-phase motor input current is calculated before applying a duty margin and utilization category.", ["I = Pout / (√3 × VLL × pf × η)", "Iselection = I × Fduty"], [{ symbol: "I", meaning: "Estimated load current", unit: "A" }, { symbol: "Pout", meaning: "Motor output power", unit: "W" }, { symbol: "η", meaning: "Motor efficiency" }, { symbol: "Fduty", meaning: "Preliminary operating-duty margin" }], "Final AC-1 or AC-3 selection uses the exact manufacturer voltage and kW table."),
  "breaker-selectivity-calculator": make("Breaker coordination screening", "The generic screen compares current ratings, B/C/D magnetic bands, and breaking capacity.", ["Rrating = In,up / In,down", "Imagnetic = kcurve × In", "Icn ≥ Ik"], [{ symbol: "In", meaning: "Breaker rated current", unit: "A" }, { symbol: "kcurve", meaning: "Generic magnetic-trip multiple" }, { symbol: "Icn", meaning: "Breaking capacity", unit: "kA" }, { symbol: "Ik", meaning: "Prospective fault current", unit: "kA" }], "Only a manufacturer selectivity or cascading table can confirm the exact paired devices."),
  "lightning-risk-assessment-calculator": make("Simplified lightning exposure equations", "Building dimensions define an equivalent collection area, which is combined with an approximate ground flash density.", ["Ae = L × W + 6H(L + W) + 9πH²", "Ng ≈ 0.04 × Td^1.25", "Nd = Ng × Ae × 10⁻⁶ × Cd"], [{ symbol: "Ae", meaning: "Equivalent collection area", unit: "m²" }, { symbol: "Td", meaning: "Thunderstorm days per year" }, { symbol: "Ng", meaning: "Estimated ground flash density", unit: "km⁻² year⁻¹" }, { symbol: "Cd", meaning: "Relative location factor" }], "This is an exposure screen, not the complete IEC 62305-2 component-risk calculation."),
  "enclosure-temperature-rise-calculator": make("Enclosure heat-balance equations", "Internal losses leave through exposed surfaces or forced airflow.", ["Natural cooling: ΔT = P / (U × Aeff)", "Forced air: ΔT = P / (0.33 × qv)", "Tinside = Tambient + ΔT"], [{ symbol: "P", meaning: "Internal heat loss", unit: "W" }, { symbol: "U", meaning: "Simplified overall heat-transfer coefficient", unit: "W/m²K" }, { symbol: "Aeff", meaning: "Effective exposed enclosure area", unit: "m²" }, { symbol: "qv", meaning: "Airflow", unit: "m³/h" }], "Average temperature does not reveal local hot spots."),
  "panel-heat-loss-calculator": make("Panel heat-loss total", "Only losses dissipated inside the enclosure contribute to the entered thermal load.", ["Pheat = Fsim × Σ(Pcomponent)"], [{ symbol: "Pheat", meaning: "Simultaneous internal heat load", unit: "W" }, { symbol: "Fsim", meaning: "Simultaneous heat factor" }, { symbol: "Pcomponent", meaning: "Individual component power loss", unit: "W" }], "Use manufacturer watt-loss data at the expected operating point."),
  "pv-string-sizing-calculator": make("PV string voltage equations", "Cold temperature raises module open-circuit voltage while hot temperature lowers operating voltage.", ["V(T) = VSTC × [1 + β × (T − 25°C)]", "Nmax = floor(VDC,max / Voc,cold)", "Nmin = ceil(VMPPT,min / Vmpp,hot)"], [{ symbol: "β", meaning: "Module voltage temperature coefficient", unit: "/°C" }, { symbol: "N", meaning: "Modules connected in series" }, { symbol: "Voc", meaning: "Module open-circuit voltage", unit: "V" }, { symbol: "Vmpp", meaning: "Module maximum-power voltage", unit: "V" }], "Both the inverter absolute maximum and MPPT window must be satisfied."),
  "off-grid-solar-system-calculator": make("Off-grid solar sizing equations", "Daily energy determines array energy, battery autonomy, and inverter starting capacity separately.", ["PPV = Edaily / (Hsun × ηsystem)", "Ebattery = Edaily × Dautonomy / (DOD × ηbattery)", "Cbat = 1000 × Ebattery / Vsystem"], [{ symbol: "PPV", meaning: "Required PV array power", unit: "kWp" }, { symbol: "Edaily", meaning: "Daily load energy", unit: "kWh/day" }, { symbol: "Hsun", meaning: "Peak sun hours", unit: "h/day" }, { symbol: "DOD", meaning: "Allowed depth of discharge" }], "Seasonal hourly simulation is required for a firm system design."),
  "spd-backup-fuse-calculator": make("SPD backup-protection rules", "Backup protection must follow the exact SPD datasheet and withstand the installation fault current.", ["In,backup ≤ In,backup,max(SPD)", "Icn,backup ≥ Ik"], [{ symbol: "In,backup", meaning: "Backup fuse or breaker rating", unit: "A" }, { symbol: "Icn,backup", meaning: "Backup device breaking capacity", unit: "kA" }, { symbol: "Ik", meaning: "Prospective short-circuit current", unit: "kA" }], "A generic device is not interchangeable with the manufacturer-approved backup device."),
  "earth-fault-loop-impedance-calculator": make("Earth fault loop impedance equations", "The complete loop is compared with the maximum that produces the required protective-device operating current.", ["Zs = Ze + Ft × (R1 + R2)", "Zs,max = U0 / Ia", "If = U0 / Zs"], [{ symbol: "Zs", meaning: "Earth fault loop impedance", unit: "Ω" }, { symbol: "Ze", meaning: "External loop impedance", unit: "Ω" }, { symbol: "Ia", meaning: "Current causing operation in the required time", unit: "A" }, { symbol: "U0", meaning: "Nominal voltage to earth", unit: "V" }], "Use the current local table or exact device curve for the required disconnection time."),
  "cable-derating-factor-calculator": make("Cable derating equation", "Independent correction factors multiply the reference ampacity.", ["Iz,corrected = Iz,reference × Ca × Cg × Ci × Cs"], [{ symbol: "Iz", meaning: "Cable current-carrying capacity", unit: "A" }, { symbol: "Ca", meaning: "Ambient-temperature factor" }, { symbol: "Cg", meaning: "Grouping factor" }, { symbol: "Ci", meaning: "Installation factor" }, { symbol: "Cs", meaning: "Soil thermal factor" }], "Replace screening factors with values from the adopted installation table."),
  "maximum-demand-calculator": make("Maximum demand equations", "Category demand is calculated first and the overall simultaneity factor is then applied.", ["Pcategory = Pconnected × Fdemand", "Pmax = Fsim × Σ(Pcategory)", "I = Pmax / (√3 × VLL × pf)"], [{ symbol: "Pmax", meaning: "Maximum simultaneous active power", unit: "kW" }, { symbol: "Fdemand", meaning: "Category demand factor" }, { symbol: "Fsim", meaning: "Overall simultaneity factor" }], "Demand factors should come from project criteria, measured data, or applicable guidance."),
  "protective-conductor-size-calculator": make("Protective conductor adiabatic equation", "The PE conductor must withstand fault energy until the protective device clears.", ["Smin = I × √t / k", "I²t ≤ k²S²"], [{ symbol: "S", meaning: "Protective conductor cross-section", unit: "mm²" }, { symbol: "I", meaning: "Earth fault current", unit: "A" }, { symbol: "t", meaning: "Clearing time", unit: "s" }, { symbol: "k", meaning: "Material and insulation thermal constant", unit: "A√s/mm²" }], "Mechanical minimums and fault-loop requirements are separate checks."),
  "cable-short-circuit-thermal-calculator": make("Cable short-circuit thermal equation", "The same adiabatic relationship can check required area, maximum time, or withstand energy.", ["I²t ≤ k²S²", "Smin = I × √t / k", "tmax = (kS / I)²"], [{ symbol: "I", meaning: "Short-circuit current", unit: "A" }, { symbol: "t", meaning: "Fault duration", unit: "s" }, { symbol: "S", meaning: "Conductor cross-section", unit: "mm²" }, { symbol: "k", meaning: "Conductor and insulation constant", unit: "A√s/mm²" }], "Use the exact protective-device clearing time at the calculated fault current."),
  "motor-starting-voltage-drop-calculator": make("Motor starting voltage-drop equations", "Starting method changes the locked-rotor current applied to the source impedance.", ["IFLC = Pout / (√3 × VLL × pf × η)", "Istart = IFLC × KLRC × Kmethod", "ΔV% ≈ Istart × |Zsource| / Vphase × 100"], [{ symbol: "IFLC", meaning: "Motor full-load current", unit: "A" }, { symbol: "KLRC", meaning: "DOL locked-rotor current multiple" }, { symbol: "Kmethod", meaning: "Starting-method current factor" }, { symbol: "Zsource", meaning: "Transformer plus feeder impedance magnitude", unit: "Ω" }], "Critical systems need a complex-impedance dynamic motor-start study."),
  "vfd-sizing-protection-calculator": make("VFD current and panel equations", "VFD selection starts with motor nameplate current, duty, environmental derating, and the drive manufacturer's output-current table.", ["Imotor = Pout / (√3 × VLL × pf × ηmotor)", "IVFD,min = max(Inameplate, Imotor) × Fduty × Fmargin / (Ftemp × Falt)", "Ploss,VFD ≈ Pmotor,input × (1/ηVFD − 1)"], [{ symbol: "IVFD,min", meaning: "Minimum continuous VFD output-current rating", unit: "A" }, { symbol: "Fduty", meaning: "Application-duty screening factor" }, { symbol: "Ftemp", meaning: "Ambient-temperature derating factor" }, { symbol: "Falt", meaning: "Altitude derating factor" }, { symbol: "Ploss,VFD", meaning: "Estimated heat dissipated by the VFD", unit: "W" }], "Replace every generic factor with the exact VFD manufacturer's normal-duty or heavy-duty table before selection."),
  "arc-flash-incident-energy-calculator": make("IEEE 1584-2018 arc-flash calculation", "The empirical model calculates arcing current at voltage anchor points, applies geometry and enclosure corrections, then repeats the energy calculation for reduced arcing current.", ["Iarc,min = Iarc × (1 − 0.5 × VarCf)", "E = IEEE1584(Voc, Ibf, Iarc, G, D, EC, CF, t)", "AFB: E(AFB) = 1.2 cal/cm²"], [{ symbol: "Iarc", meaning: "Predicted normal arcing current", unit: "kA" }, { symbol: "Iarc,min", meaning: "Reduced arcing current used for the second clearing-time scenario", unit: "kA" }, { symbol: "Ibf", meaning: "Bolted three-phase fault current", unit: "kA" }, { symbol: "G", meaning: "Conductor gap", unit: "mm" }, { symbol: "D", meaning: "Working distance", unit: "mm" }, { symbol: "EC", meaning: "Electrode configuration" }, { symbol: "CF", meaning: "Enclosure size correction factor" }, { symbol: "AFB", meaning: "Arc-flash boundary", unit: "mm" }], "IEEE 1584 predicts thermal incident energy and boundary; it does not select PPE or authorize energized work.")
};
