import type { ToolDefinition, ToolField } from "./types";

const phaseField: ToolField = { id: "phase", label: "System", type: "select", defaultValue: "single", options: [{ value: "dc", label: "DC" }, { value: "single", label: "Single-phase AC" }, { value: "three", label: "Three-phase AC" }] };
const standardWarning = "Preliminary engineering estimate only. Verify the final design against the current applicable standard, local rules, manufacturer data, and project conditions.";
const contact = [{ label: "VIOX engineering support", href: "https://viox.com/contact" }];
const faq = (name: string) => [{ question: `Can this ${name} replace a final design?`, answer: "No. It is a transparent preliminary calculation. Final equipment selection requires the applicable rules, exact product data, and qualified review." }];

export const expansionTools: ToolDefinition[] = [
  {
    slug: "ohms-law-calculator", title: "Ohm's Law Calculator", shortTitle: "Ohm's Law", category: "basic-conversion",
    description: "Enter any two of voltage, current, resistance, and power to calculate the other two electrical quantities.", intent: "Solve DC or purely resistive Ohm's law relationships from any two known values.",
    fields: [{ id: "solveFrom", label: "Known quantities", type: "select", defaultValue: "vi", options: [{ value: "vi", label: "Voltage + current" }, { value: "vr", label: "Voltage + resistance" }, { value: "vp", label: "Voltage + power" }, { value: "ir", label: "Current + resistance" }, { value: "ip", label: "Current + power" }, { value: "rp", label: "Resistance + power" }] }, { id: "voltage", label: "Voltage", type: "number", defaultValue: 230, unit: "V", min: 0 }, { id: "current", label: "Current", type: "number", defaultValue: 2, unit: "A", min: 0 }, { id: "resistance", label: "Resistance", type: "number", defaultValue: 115, unit: "Ω", min: 0 }, { id: "power", label: "Power", type: "number", defaultValue: 460, unit: "W", min: 0 }],
    formula: "V = I × R; P = V × I = I²R = V²/R.", assumptions: ["DC or purely resistive steady-state circuit", "Both entered values describe the same operating point"], warnings: [standardWarning], faqs: faq("Ohm's law calculation"), relatedTools: ["watts-amps-volts-calculator", "resistor-series-parallel-calculator", "terminal-heating-calculator"], relatedProducts: contact, keywords: ["ohms law calculator", "voltage current resistance calculator", "watts ohms amps calculator"]
  },
  {
    slug: "watts-amps-volts-calculator", title: "Watts to Amps and Volts Calculator", shortTitle: "Watts / Amps / Volts", category: "basic-conversion",
    description: "Convert watts, amps, and volts for DC, single-phase, or three-phase systems with common voltage presets.", intent: "Answer consumer and installer watts-to-amps conversion questions without confusing phase formulas.",
    fields: [{ id: "knownQuantities", label: "Known quantities", type: "select", defaultValue: "pv", options: [{ value: "pv", label: "Power + voltage" }, { value: "iv", label: "Current + voltage" }, { value: "pi", label: "Power + current" }] }, phaseField, { id: "power", label: "Power", type: "number", defaultValue: 3000, unit: "W", min: 0 }, { id: "current", label: "Current", type: "number", defaultValue: 13, unit: "A", min: 0 }, { id: "voltage", label: "Voltage", type: "number", defaultValue: 230, unit: "V", min: 0 }, { id: "powerFactor", label: "Power factor", type: "number", defaultValue: 1, min: 0.01, max: 1, step: 0.01, showWhen: { field: "phase", values: ["single", "three"] } }],
    formula: "DC: P = VI; single-phase: P = VIpf; three-phase: P = √3VIpf.", assumptions: ["Balanced three-phase load", "Voltage is line-to-line for three-phase"], warnings: [standardWarning], faqs: faq("watts, amps, and volts conversion"), relatedTools: ["ohms-law-calculator", "kw-kva-amp-calculator", "circuit-breaker-size-calculator"], relatedProducts: contact, keywords: ["watts to amps", "amps to watts", "watts amps volts calculator"]
  },
  {
    slug: "ev-charging-time-cost-calculator", title: "EV Charging Time and Cost Calculator", shortTitle: "EV Charge Time", category: "ev-charging",
    description: "Estimate EV charging time, delivered energy, wall energy, and cost from battery state of charge and charger power.", intent: "Plan a charging session and connect vehicle energy demand to charger and feeder planning.",
    fields: [{ id: "capacity", label: "Usable battery capacity", type: "number", defaultValue: 75, unit: "kWh", min: 0 }, { id: "startSoc", label: "Starting state of charge", type: "number", defaultValue: 20, unit: "%", min: 0, max: 100 }, { id: "targetSoc", label: "Target state of charge", type: "number", defaultValue: 80, unit: "%", min: 0, max: 100 }, { id: "chargerPower", label: "Charging power", type: "number", defaultValue: 11, unit: "kW", min: 0 }, { id: "efficiency", label: "Charging efficiency", type: "number", defaultValue: 90, unit: "%", min: 1, max: 100 }, { id: "tariff", label: "Electricity price", type: "number", defaultValue: 0.2, unit: "/kWh", min: 0 }],
    formula: "Battery energy = capacity × ΔSOC; wall energy = battery energy / efficiency; time = wall energy / charger power.", assumptions: ["Constant average charging power", "Battery capacity is usable capacity", "Tapering and thermal limits are represented only by average power"], warnings: [standardWarning], faqs: faq("EV charging estimate"), relatedTools: ["ev-charger-load-calculator", "energy-cost-calculator", "rcd-rcbo-selector"], relatedProducts: [{ label: "VIOX EV charging protection", href: "https://viox.com/ev-charger/" }], keywords: ["ev charging time calculator", "electric car charging cost", "how long to charge an ev"]
  },
  {
    slug: "battery-charging-time-calculator", title: "Battery Charging Time Calculator", shortTitle: "Battery Charge Time", category: "basic-conversion",
    description: "Calculate battery charging time from Ah and current or kWh and charger power, including charging efficiency.", intent: "Estimate general lithium, lead-acid, and storage-battery charging duration.",
    fields: [{ id: "basis", label: "Input method", type: "select", defaultValue: "ah", options: [{ value: "ah", label: "Ah and charging current" }, { value: "kwh", label: "kWh and charging power" }] }, { id: "capacityAh", label: "Battery capacity", type: "number", defaultValue: 100, unit: "Ah", min: 0, showWhen: { field: "basis", values: ["ah"] } }, { id: "current", label: "Charging current", type: "number", defaultValue: 20, unit: "A", min: 0, showWhen: { field: "basis", values: ["ah"] } }, { id: "capacityKwh", label: "Battery energy", type: "number", defaultValue: 5, unit: "kWh", min: 0, showWhen: { field: "basis", values: ["kwh"] } }, { id: "power", label: "Charging power", type: "number", defaultValue: 1, unit: "kW", min: 0, showWhen: { field: "basis", values: ["kwh"] } }, { id: "startSoc", label: "Starting SOC", type: "number", defaultValue: 20, unit: "%", min: 0, max: 100 }, { id: "targetSoc", label: "Target SOC", type: "number", defaultValue: 100, unit: "%", min: 0, max: 100 }, { id: "efficiency", label: "Charging efficiency", type: "number", defaultValue: 85, unit: "%", min: 1, max: 100 }],
    formula: "Time = required Ah/(charging current × efficiency), or required kWh/(charging power × efficiency).", assumptions: ["Average current or power remains constant", "SOC is proportional to available capacity"], warnings: [standardWarning], faqs: faq("battery charging-time estimate"), relatedTools: ["battery-c-rate-runtime-calculator", "ev-charging-time-cost-calculator", "electrical-unit-converter"], relatedProducts: contact, keywords: ["battery charging time calculator", "ah charging time", "kwh charge time"]
  },
  {
    slug: "resistor-series-parallel-calculator", title: "Series and Parallel Resistor Calculator", shortTitle: "Resistor Network", category: "basic-conversion",
    description: "Calculate equivalent resistance, current, and voltage or current division for up to four resistors.", intent: "Provide a fast educational and DIY resistor-network calculation.",
    fields: [{ id: "connection", label: "Connection", type: "select", defaultValue: "series", options: [{ value: "series", label: "Series" }, { value: "parallel", label: "Parallel" }] }, { id: "r1", label: "R1", type: "number", defaultValue: 100, unit: "Ω", min: 0 }, { id: "r2", label: "R2", type: "number", defaultValue: 220, unit: "Ω", min: 0 }, { id: "r3", label: "R3", type: "number", defaultValue: 330, unit: "Ω", min: 0 }, { id: "r4", label: "R4", type: "number", defaultValue: 470, unit: "Ω", min: 0 }, { id: "supplyVoltage", label: "Supply voltage", type: "number", defaultValue: 12, unit: "V", min: 0 }],
    formula: "Series: Req = ΣR; parallel: 1/Req = Σ(1/R).", assumptions: ["Ideal linear resistors", "All four entered resistor values are connected"], warnings: ["Check resistor voltage and power ratings before construction."], faqs: faq("resistor-network calculation"), relatedTools: ["ohms-law-calculator", "terminal-heating-calculator", "electrical-unit-converter"], relatedProducts: contact, keywords: ["resistors in parallel calculator", "series resistor calculator", "equivalent resistance"]
  },
  {
    slug: "electrical-unit-converter", title: "Electrical Unit Converter", shortTitle: "Unit Converter", category: "basic-conversion",
    description: "Convert power and energy units in either direction, or calculate DC, single-phase, and three-phase current from power.", intent: "Keep power, energy, and phase-current conversions separate so every visible field belongs to the selected task.",
    fields: [{ id: "quantity", label: "Mode", type: "select", defaultValue: "power", options: [{ value: "power", label: "Power" }, { value: "energy", label: "Energy" }, { value: "current", label: "Phase current" }] }, { id: "leftValue", label: "Left value", type: "number", defaultValue: 1, min: 0 }, { id: "rightValue", label: "Right value", type: "number", defaultValue: 1.34102, min: 0 }, { id: "inputSide", label: "Edited side", type: "select", defaultValue: "left", options: [{ value: "left", label: "Left" }, { value: "right", label: "Right" }] }, { id: "fromUnit", label: "From unit", type: "select", defaultValue: "kw", options: [{ value: "w", label: "W" }, { value: "kw", label: "kW" }, { value: "mw", label: "MW" }, { value: "hp", label: "mechanical hp" }, { value: "btuh", label: "BTU/h" }] }, { id: "toUnit", label: "To unit", type: "select", defaultValue: "hp", options: [{ value: "w", label: "W" }, { value: "kw", label: "kW" }, { value: "mw", label: "MW" }, { value: "hp", label: "mechanical hp" }, { value: "btuh", label: "BTU/h" }] }, { id: "phasePower", label: "Power", type: "number", defaultValue: 10, min: 0 }, { id: "phasePowerUnit", label: "Power unit", type: "select", defaultValue: "kw", options: [{ value: "w", label: "W" }, { value: "kw", label: "kW" }, { value: "mw", label: "MW" }] }, phaseField, { id: "voltage", label: "Voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "powerFactor", label: "Power factor", type: "number", defaultValue: 0.9, min: 0.01, max: 1 }],
    formula: "Power is converted through watts, energy through joules, and current uses I = P/V, I = P/(Vpf), or I = P/(√3Vpf).", assumptions: ["Mechanical horsepower = 745.699872 W", "International Table BTU = 1055.05585262 J", "Three-phase voltage is line-to-line"], warnings: ["Power and energy are different quantities and cannot be converted without a duration."], faqs: faq("unit conversion"), relatedTools: ["watts-amps-volts-calculator", "kw-kva-amp-calculator", "battery-charging-time-calculator"], relatedProducts: contact, keywords: ["electrical unit converter", "kw to hp", "kwh to joules", "btu to kw", "three phase current calculator"]
  },
  {
    slug: "contactor-selection-calculator", title: "Contactor Selection Calculator (AC-1 / AC-3)", shortTitle: "Contactor Selector", category: "motor-control",
    description: "Estimate a contactor current class from load type, power, voltage, utilization category, and operating frequency.", intent: "Screen AC-1 resistive and AC-3 squirrel-cage motor contactor duty.",
    fields: [{ id: "loadType", label: "Load type", type: "select", defaultValue: "motor", options: [{ value: "motor", label: "Squirrel-cage motor" }, { value: "resistive", label: "Resistive / heating" }, { value: "mixed", label: "Mixed or inductive load" }] }, { id: "power", label: "Load power", type: "number", defaultValue: 15, unit: "kW", min: 0 }, { id: "voltage", label: "Line voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "powerFactor", label: "Power factor", type: "number", defaultValue: 0.85, min: 0.01, max: 1 }, { id: "efficiency", label: "Efficiency", type: "number", defaultValue: 90, unit: "%", min: 1, max: 100 }, { id: "operations", label: "Operations per hour", type: "number", defaultValue: 30, unit: "/h", min: 0 }],
    formula: "Three-phase motor current = P/(√3Vpfη); selection current applies a duty margin and AC-3 or AC-1 category.", assumptions: ["Three-phase load", "AC-3 applies to normal starting and switching off a running squirrel-cage motor"], warnings: [standardWarning, "Frequent inching, plugging, reversing, capacitor, transformer, or lighting duty needs the matching utilization category and manufacturer tables."], faqs: faq("contactor selection"), relatedTools: ["motor-current-calculator", "motor-starter-selection-calculator", "mcb-inrush-compatibility-checker"], relatedProducts: [{ label: "VIOX AC contactors", href: "https://viox.com/ac-contactor/" }], keywords: ["contactor selection calculator", "ac3 contactor sizing", "ac1 contactor rating"]
  },
  {
    slug: "breaker-selectivity-calculator", title: "Circuit Breaker Selectivity and Cascading Checker", shortTitle: "Breaker Selectivity", category: "circuit-protection",
    description: "Screen upstream and downstream breaker rating, curve, breaking capacity, and fault-current coordination.", intent: "Flag obvious rating, instantaneous-band, and breaking-capacity conflicts before manufacturer coordination-table review.",
    fields: [{ id: "upstreamRating", label: "Upstream breaker rating", type: "number", defaultValue: 100, unit: "A", min: 0 }, { id: "upstreamCurve", label: "Upstream trip curve", type: "select", defaultValue: "c", options: [{ value: "b", label: "B curve" }, { value: "c", label: "C curve" }, { value: "d", label: "D curve" }] }, { id: "upstreamBreaking", label: "Upstream breaking capacity", type: "number", defaultValue: 25, unit: "kA", min: 0 }, { id: "downstreamRating", label: "Downstream breaker rating", type: "number", defaultValue: 32, unit: "A", min: 0 }, { id: "downstreamCurve", label: "Downstream trip curve", type: "select", defaultValue: "c", options: [{ value: "b", label: "B curve" }, { value: "c", label: "C curve" }, { value: "d", label: "D curve" }] }, { id: "downstreamBreaking", label: "Downstream breaking capacity", type: "number", defaultValue: 10, unit: "kA", min: 0 }, { id: "faultCurrent", label: "Prospective fault current", type: "number", defaultValue: 6, unit: "kA", min: 0 }],
    formula: "The checker compares rating ratio, approximate B/C/D instantaneous bands, and each device's entered breaking capacity.", assumptions: ["Generic B/C/D magnetic bands only", "No manufacturer energy-selectivity or cascading table is embedded"], warnings: [standardWarning, "A positive screening result is not proof of selectivity or backup protection; use the exact paired-device manufacturer table."], faqs: faq("breaker coordination screening"), relatedTools: ["mcb-inrush-compatibility-checker", "short-circuit-current-calculator", "circuit-breaker-size-calculator"], relatedProducts: [{ label: "VIOX MCB and MCCB", href: "https://viox.com/mcb/" }], keywords: ["circuit breaker selectivity calculator", "breaker coordination", "cascading backup protection"]
  },
  {
    slug: "lightning-risk-assessment-calculator", title: "Lightning Risk Assessment Calculator", shortTitle: "Lightning Risk", category: "surge-protection",
    description: "Estimate a simplified lightning exposure score from building collection area, location, thunderstorm activity, and incoming lines.", intent: "Provide an upstream screening step for IEC 62305 risk review and SPD planning.",
    fields: [{ id: "length", label: "Building length", type: "number", defaultValue: 30, unit: "m", min: 0 }, { id: "width", label: "Building width", type: "number", defaultValue: 20, unit: "m", min: 0 }, { id: "height", label: "Building height", type: "number", defaultValue: 10, unit: "m", min: 0 }, { id: "thunderDays", label: "Thunderstorm days per year", type: "number", defaultValue: 30, unit: "days", min: 0 }, { id: "location", label: "Relative location", type: "select", defaultValue: "surrounded", options: [{ value: "surrounded", label: "Surrounded by similar objects" }, { value: "isolated", label: "Isolated structure" }, { value: "hill", label: "Hilltop or prominent location" }] }, { id: "powerLine", label: "Incoming power line", type: "select", defaultValue: "overhead", options: [{ value: "underground", label: "Underground" }, { value: "overhead", label: "Overhead" }, { value: "mixed", label: "Mixed" }] }, { id: "consequence", label: "Consequence level", type: "select", defaultValue: "normal", options: [{ value: "normal", label: "Normal occupancy" }, { value: "critical", label: "Critical service / high consequence" }] }],
    formula: "Collection area Ae = LW + 6H(L+W) + 9πH²; annual strike exposure uses a thunder-day-derived ground flash-density approximation.", assumptions: ["Simplified screening, not the complete IEC 62305-2 component-risk method", "Thunderstorm days are converted to a broad flash-density estimate"], warnings: [standardWarning, "Do not describe this score as a formal IEC 62305 risk assessment."], faqs: faq("lightning-risk screening"), relatedTools: ["spd-calculator", "advanced-spd-selection-calculator", "pv-combiner-box-sizing-calculator"], relatedProducts: [{ label: "VIOX surge protective devices", href: "https://viox.com/spd/" }], keywords: ["lightning risk assessment calculator", "iec 62305 calculator", "lightning protection risk"]
  },
  {
    slug: "enclosure-temperature-rise-calculator", title: "Enclosure Temperature Rise Calculator", shortTitle: "Enclosure Temperature", category: "panel-design",
    description: "Estimate cabinet temperature rise from enclosure dimensions, internal heat, installation condition, and cooling method.", intent: "Screen whether natural cooling, forced ventilation, or active cooling deserves detailed review.",
    fields: [{ id: "width", label: "Enclosure width", type: "number", defaultValue: 800, unit: "mm", min: 0 }, { id: "height", label: "Enclosure height", type: "number", defaultValue: 1200, unit: "mm", min: 0 }, { id: "depth", label: "Enclosure depth", type: "number", defaultValue: 300, unit: "mm", min: 0 }, { id: "mounting", label: "Installation", type: "select", defaultValue: "wall", options: [{ value: "free", label: "Free-standing, all sides exposed" }, { value: "wall", label: "Wall-mounted" }, { value: "recessed", label: "Partly recessed / grouped" }] }, { id: "heat", label: "Internal heat loss", type: "number", defaultValue: 250, unit: "W", min: 0 }, { id: "ambient", label: "Ambient temperature", type: "number", defaultValue: 35, unit: "°C" }, { id: "airflow", label: "Forced airflow", type: "number", defaultValue: 0, unit: "m³/h", min: 0 }],
    formula: "Natural estimate: ΔT = P/(U×Aeffective); forced-air estimate: ΔT = P/(0.33×airflow), using a conservative enclosure heat-transfer coefficient.", assumptions: ["Uniform internal heat distribution", "Steady ambient and airflow", "Simplified heat-transfer coefficient, not a full IEC 60890 calculation"], warnings: [standardWarning, "Hot spots and component temperature limits may govern even when average enclosure temperature appears acceptable."], faqs: faq("enclosure temperature-rise estimate"), relatedTools: ["panel-heat-loss-calculator", "terminal-heating-calculator", "busbar-current-rating-calculator"], relatedProducts: [{ label: "VIOX electrical enclosures", href: "https://viox.com/enclosures/" }], keywords: ["enclosure temperature rise calculator", "electrical cabinet cooling", "panel heat dissipation"]
  },
  {
    slug: "panel-heat-loss-calculator", title: "Panel Component Heat Loss Calculator", shortTitle: "Panel Heat Loss", category: "panel-design",
    description: "Add breaker, contactor, drive, power-supply, transformer, and miscellaneous losses to estimate total cabinet heat load.", intent: "Create the internal heat input required by the enclosure temperature-rise calculator.",
    fields: [{ id: "breakers", label: "Breaker losses", type: "number", defaultValue: 30, unit: "W", min: 0 }, { id: "contactors", label: "Contactor and relay losses", type: "number", defaultValue: 25, unit: "W", min: 0 }, { id: "drives", label: "VFD / drive losses", type: "number", defaultValue: 150, unit: "W", min: 0 }, { id: "powerSupplies", label: "Power-supply losses", type: "number", defaultValue: 20, unit: "W", min: 0 }, { id: "transformers", label: "Transformer losses", type: "number", defaultValue: 40, unit: "W", min: 0 }, { id: "other", label: "Other component losses", type: "number", defaultValue: 15, unit: "W", min: 0 }, { id: "diversity", label: "Simultaneous heat factor", type: "number", defaultValue: 100, unit: "%", min: 0, max: 100 }],
    formula: "Total heat = diversity × Σ component power losses.", assumptions: ["Entered values are losses dissipated inside the enclosure", "The simultaneous factor applies to all entered groups"], warnings: ["Use manufacturer watt-loss data at the actual load, coil voltage, switching frequency, and operating state."], faqs: faq("panel heat-load total"), relatedTools: ["enclosure-temperature-rise-calculator", "terminal-heating-calculator", "energy-cost-calculator"], relatedProducts: [{ label: "VIOX panel components", href: "https://viox.com/products/" }], keywords: ["panel heat loss calculator", "cabinet component watt loss", "electrical enclosure heat load"]
  },
  {
    slug: "pv-string-sizing-calculator", title: "PV String Sizing Calculator", shortTitle: "PV String Size", category: "solar-storage",
    description: "Calculate temperature-corrected PV string voltage and the allowable module count for an inverter MPPT window.", intent: "Place module string design upstream of combiner-box, DC breaker, fuse, and SPD selection.",
    fields: [{ id: "voc", label: "Module Voc at STC", type: "number", defaultValue: 49.5, unit: "V", min: 0 }, { id: "vmpp", label: "Module Vmpp at STC", type: "number", defaultValue: 41.5, unit: "V", min: 0 }, { id: "vocCoeff", label: "Voc temperature coefficient", type: "number", defaultValue: -0.28, unit: "%/°C", max: 0 }, { id: "vmppCoeff", label: "Vmpp temperature coefficient", type: "number", defaultValue: -0.35, unit: "%/°C", max: 0 }, { id: "minTemp", label: "Minimum cell temperature", type: "number", defaultValue: -10, unit: "°C" }, { id: "maxTemp", label: "Maximum cell temperature", type: "number", defaultValue: 70, unit: "°C" }, { id: "maxDcVoltage", label: "Inverter maximum DC voltage", type: "number", defaultValue: 1100, unit: "V", min: 0 }, { id: "mpptMin", label: "MPPT minimum voltage", type: "number", defaultValue: 200, unit: "V", min: 0 }, { id: "mpptMax", label: "MPPT maximum voltage", type: "number", defaultValue: 1000, unit: "V", min: 0 }],
    formula: "V(T) = VSTC[1 + coefficient(T-25°C)]; maximum modules use cold Voc, minimum modules use hot Vmpp.", assumptions: ["Entered temperatures are conservative cell temperatures", "Linear datasheet coefficients around STC"], warnings: [standardWarning, "Use the inverter's absolute maximum voltage separately from its MPPT operating window."], faqs: faq("PV string sizing"), relatedTools: ["pv-combiner-box-sizing-calculator", "advanced-spd-selection-calculator", "off-grid-solar-system-calculator"], relatedProducts: [{ label: "VIOX PV protection", href: "https://viox.com/combiner-box/" }], keywords: ["pv string sizing calculator", "solar panels per string", "mppt string voltage calculator"]
  },
  {
    slug: "off-grid-solar-system-calculator", title: "Off-Grid Solar System Sizing Calculator", shortTitle: "Off-Grid Solar", category: "solar-storage",
    description: "Estimate PV array, battery-bank capacity, and inverter power from daily energy, sun hours, autonomy, and system voltage.", intent: "Create a transparent first-pass module, battery, and inverter sizing workflow.",
    fields: [{ id: "dailyEnergy", label: "Daily energy use", type: "number", defaultValue: 10, unit: "kWh/day", min: 0 }, { id: "sunHours", label: "Peak sun hours", type: "number", defaultValue: 4.5, unit: "h/day", min: 0 }, { id: "systemEfficiency", label: "Overall system efficiency", type: "number", defaultValue: 75, unit: "%", min: 1, max: 100 }, { id: "modulePower", label: "PV module rated power", type: "number", defaultValue: 550, unit: "W", min: 0 }, { id: "autonomy", label: "Battery autonomy", type: "number", defaultValue: 2, unit: "days", min: 0 }, { id: "dod", label: "Maximum depth of discharge", type: "number", defaultValue: 80, unit: "%", min: 1, max: 100 }, { id: "batteryEfficiency", label: "Battery efficiency", type: "number", defaultValue: 90, unit: "%", min: 1, max: 100 }, { id: "systemVoltage", label: "Battery system voltage", type: "number", defaultValue: 48, unit: "V", min: 0 }, { id: "peakLoad", label: "Maximum simultaneous load", type: "number", defaultValue: 5, unit: "kW", min: 0 }, { id: "surgeFactor", label: "Inverter surge margin", type: "number", defaultValue: 125, unit: "%", min: 100 }],
    formula: "PV kW = daily kWh/(sun hours×system efficiency); battery kWh = daily kWh×autonomy/(DOD×battery efficiency).", assumptions: ["Average daily energy and peak-sun-hours inputs are representative", "No seasonal simulation or battery aging model"], warnings: [standardWarning], faqs: faq("off-grid solar sizing"), relatedTools: ["pv-string-sizing-calculator", "battery-c-rate-runtime-calculator", "pv-combiner-box-sizing-calculator"], relatedProducts: [{ label: "VIOX DC solar protection", href: "https://viox.com/dc-mcb/" }], keywords: ["off grid solar system calculator", "solar battery sizing", "inverter size calculator"]
  },
  {
    slug: "spd-backup-fuse-calculator", title: "SPD Backup Fuse Selection Calculator", shortTitle: "SPD Backup Fuse", category: "surge-protection",
    description: "Screen an SPD backup fuse or MCB rating from the SPD datasheet maximum backup protection and prospective fault current.", intent: "Connect SPD and fuse product selection without inventing device coordination data.",
    fields: [{ id: "spdType", label: "SPD duty", type: "select", defaultValue: "type2", options: [{ value: "type1", label: "Type 1 or Type 1+2" }, { value: "type2", label: "Type 2" }, { value: "pv", label: "PV / DC SPD" }] }, { id: "maxBackup", label: "SPD datasheet maximum backup fuse", type: "number", defaultValue: 125, unit: "A", min: 0 }, { id: "upstreamProtection", label: "Existing upstream protective device", type: "number", defaultValue: 160, unit: "A", min: 0 }, { id: "faultCurrent", label: "Prospective short-circuit current", type: "number", defaultValue: 10, unit: "kA", min: 0 }, { id: "deviceBreaking", label: "Candidate backup-device breaking capacity", type: "number", defaultValue: 25, unit: "kA", min: 0 }, { id: "preferred", label: "Backup device", type: "select", defaultValue: "fuse", options: [{ value: "fuse", label: "gG fuse" }, { value: "mcb", label: "MCB / breaker, if SPD-approved" }] }],
    formula: "The candidate rating must not exceed the SPD manufacturer's maximum backup protection and its breaking capacity must exceed prospective fault current.", assumptions: ["Maximum backup value comes from the exact SPD datasheet", "No generic fuse or breaker can substitute for manufacturer coordination approval"], warnings: [standardWarning, "If the SPD manufacturer specifies a particular device or no external backup device, follow that instruction."], faqs: faq("SPD backup protection screen"), relatedTools: ["advanced-spd-selection-calculator", "fuse-sizing-calculator", "short-circuit-current-calculator"], relatedProducts: [{ label: "VIOX SPD and fuse products", href: "https://viox.com/spd/" }], keywords: ["spd backup fuse calculator", "surge protector backup fuse", "spd mcb size"]
  },
  {
    slug: "earth-fault-loop-impedance-calculator", title: "Earth Fault Loop Impedance Calculator (Zs)", shortTitle: "Earth Loop Zs", category: "circuit-protection",
    description: "Calculate actual earth fault loop impedance and compare it with a device-based maximum Zs input.", intent: "Support IEC 60364-4-41 and BS 7671 disconnection screening without reproducing proprietary tables.",
    fields: [{ id: "deviceType", label: "Protective device", type: "select", defaultValue: "mcb", options: [{ value: "mcb", label: "MCB / breaker" }, { value: "fuse", label: "Fuse" }, { value: "rcd", label: "RCD-assisted fault protection" }] }, { id: "voltageToEarth", label: "Nominal voltage to earth", type: "number", defaultValue: 230, unit: "V", min: 0 }, { id: "deviceRating", label: "Protective-device rating", type: "number", defaultValue: 32, unit: "A", min: 0 }, { id: "disconnectionTime", label: "Required disconnection time", type: "number", defaultValue: 0.4, unit: "s", min: 0 }, { id: "instantMultiple", label: "Required operating-current multiple", type: "number", defaultValue: 10, unit: "×In", min: 0 }, { id: "ze", label: "External loop impedance Ze", type: "number", defaultValue: 0.35, unit: "Ω", min: 0 }, { id: "r1", label: "Line-conductor resistance R1", type: "number", defaultValue: 0.3, unit: "Ω", min: 0 }, { id: "r2", label: "Protective-conductor resistance R2", type: "number", defaultValue: 0.3, unit: "Ω", min: 0 }, { id: "temperatureFactor", label: "Conductor temperature factor", type: "number", defaultValue: 1.2, min: 1 }, { id: "tabulatedMaxZs", label: "Applicable tabulated maximum Zs", type: "number", defaultValue: 0.72, unit: "Ω", min: 0, help: "Enter the value from the current local standard or device data when it governs." }],
    formula: "Zs(actual) = Ze + temperature factor×(R1+R2); formula limit = U0/Ia.", assumptions: ["Entered resistances represent the complete circuit path", "Operating-current multiple is selected for the required disconnection time"], warnings: [standardWarning], faqs: faq("earth-fault loop check"), relatedTools: ["circuit-breaker-size-calculator", "cable-size-calculator", "short-circuit-current-calculator"], relatedProducts: [{ label: "VIOX circuit breakers", href: "https://viox.com/mcb/" }], keywords: ["zs calculator", "earth fault loop impedance", "maximum zs calculator"]
  },
  {
    slug: "cable-derating-factor-calculator", title: "Cable Derating Factor Calculator", shortTitle: "Cable Derating", category: "cable-wiring",
    description: "Combine ambient-temperature, grouping, installation, and soil factors to estimate corrected cable ampacity.", intent: "Provide transparent typical factors that feed cable sizing without reproducing full IEC tables.",
    fields: [{ id: "baseAmpacity", label: "Reference cable ampacity", type: "number", defaultValue: 100, unit: "A", min: 0 }, { id: "ambient", label: "Ambient temperature", type: "number", defaultValue: 40, unit: "°C" }, { id: "insulation", label: "Conductor insulation", type: "select", defaultValue: "xlpe", options: [{ value: "pvc", label: "PVC 70°C" }, { value: "xlpe", label: "XLPE 90°C" }] }, { id: "groupedCircuits", label: "Grouped loaded circuits", type: "number", defaultValue: 3, min: 1 }, { id: "installation", label: "Installation severity", type: "select", defaultValue: "open", options: [{ value: "open", label: "Open / ventilated" }, { value: "enclosed", label: "Enclosed / trunking" }, { value: "insulated", label: "Surrounded by thermal insulation" }, { value: "buried", label: "Direct buried" }] }, { id: "soilResistivity", label: "Soil thermal resistivity", type: "number", defaultValue: 2.5, unit: "K·m/W", min: 0, showWhen: { field: "installation", values: ["buried"] } }],
    formula: "Corrected ampacity = reference ampacity × Ca × Cg × Ci × Cs.", assumptions: ["Factors are typical screening values, not a reproduction of a complete IEC 60364-5-52 national table", "All grouped circuits are substantially loaded"], warnings: [standardWarning], faqs: faq("cable derating calculation"), relatedTools: ["cable-size-calculator", "voltage-drop-calculator", "cable-short-circuit-thermal-calculator"], relatedProducts: [{ label: "VIOX cable connection products", href: "https://viox.com/cable-lug/" }], keywords: ["cable derating calculator", "cable grouping factor", "ambient temperature cable factor"]
  },
  {
    slug: "maximum-demand-calculator", title: "Maximum Demand and Diversity Calculator", shortTitle: "Maximum Demand", category: "circuit-protection",
    description: "Combine lighting, socket, HVAC, motor, EV, and other loads with demand and simultaneity factors.", intent: "Estimate incomer design power, current, and a preliminary standard breaker rating.",
    fields: [{ id: "lighting", label: "Lighting connected load", type: "number", defaultValue: 20, unit: "kW", min: 0 }, { id: "lightingFactor", label: "Lighting demand factor", type: "number", defaultValue: 90, unit: "%", min: 0, max: 100 }, { id: "sockets", label: "Socket connected load", type: "number", defaultValue: 30, unit: "kW", min: 0 }, { id: "socketFactor", label: "Socket demand factor", type: "number", defaultValue: 50, unit: "%", min: 0, max: 100 }, { id: "hvac", label: "HVAC connected load", type: "number", defaultValue: 50, unit: "kW", min: 0 }, { id: "hvacFactor", label: "HVAC demand factor", type: "number", defaultValue: 80, unit: "%", min: 0, max: 100 }, { id: "motors", label: "Motor connected load", type: "number", defaultValue: 25, unit: "kW", min: 0 }, { id: "motorFactor", label: "Motor demand factor", type: "number", defaultValue: 75, unit: "%", min: 0, max: 100 }, { id: "evOther", label: "EV and other load", type: "number", defaultValue: 20, unit: "kW", min: 0 }, { id: "evFactor", label: "EV/other demand factor", type: "number", defaultValue: 60, unit: "%", min: 0, max: 100 }, { id: "simultaneity", label: "Overall simultaneity factor", type: "number", defaultValue: 90, unit: "%", min: 0, max: 100 }, { id: "voltage", label: "Three-phase line voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "powerFactor", label: "Overall power factor", type: "number", defaultValue: 0.9, min: 0.01, max: 1 }],
    formula: "Maximum demand = simultaneity × Σ(connected category load × demand factor); I = P/(√3Vpf).", assumptions: ["Balanced three-phase incomer", "Demand factors are project inputs, not universal prescribed values"], warnings: [standardWarning], faqs: faq("maximum-demand estimate"), relatedTools: ["circuit-breaker-size-calculator", "transformer-sizing-calculator", "ev-charger-load-calculator"], relatedProducts: [{ label: "VIOX incomer protection", href: "https://viox.com/mccb/" }], keywords: ["maximum demand calculator", "electrical diversity factor", "simultaneity factor calculator"]
  },
  {
    slug: "protective-conductor-size-calculator", title: "Protective Conductor Size Calculator", shortTitle: "PE Conductor", category: "cable-wiring",
    description: "Calculate minimum protective-conductor cross-section using the IEC adiabatic equation and a user-selected material k value.", intent: "Screen PE conductor thermal withstand for a known fault current and clearing time.",
    fields: [{ id: "faultCurrent", label: "Earth fault current", type: "number", defaultValue: 5, unit: "kA", min: 0 }, { id: "clearingTime", label: "Protective-device clearing time", type: "number", defaultValue: 0.2, unit: "s", min: 0 }, { id: "k", label: "Conductor k value", type: "number", defaultValue: 115, unit: "A√s/mm²", min: 0, help: "Select k from the applicable standard for conductor, insulation, and initial/final temperatures." }, { id: "installedSize", label: "Installed PE cross-section", type: "number", defaultValue: 25, unit: "mm²", min: 0 }],
    formula: "S = I√t/k.", assumptions: ["Fault current remains constant for the entered duration", "Entered k value matches conductor material, insulation, and temperature limits"], warnings: [standardWarning, "Also check minimum mechanical cross-section, bonding requirements, terminals, and fault-loop impedance."], faqs: faq("protective-conductor adiabatic calculation"), relatedTools: ["earth-fault-loop-impedance-calculator", "cable-short-circuit-thermal-calculator", "cable-size-calculator"], relatedProducts: [{ label: "VIOX cable lugs and terminals", href: "https://viox.com/cable-lug/" }], keywords: ["protective conductor size calculator", "pe conductor adiabatic equation", "iec 60364 5 54 calculator"]
  },
  {
    slug: "cable-short-circuit-thermal-calculator", title: "Cable Short-Circuit Thermal Withstand Calculator", shortTitle: "Cable Short-Circuit", category: "cable-wiring",
    description: "Check cable short-circuit thermal withstand using conductor area, fault current, duration, and material k value.", intent: "Compare installed conductor area with the IEC adiabatic minimum or calculate allowable I²t.",
    fields: [{ id: "area", label: "Conductor cross-section", type: "number", defaultValue: 50, unit: "mm²", min: 0 }, { id: "faultCurrent", label: "Prospective short-circuit current", type: "number", defaultValue: 10, unit: "kA", min: 0 }, { id: "duration", label: "Fault duration", type: "number", defaultValue: 0.2, unit: "s", min: 0 }, { id: "k", label: "Conductor k value", type: "number", defaultValue: 115, unit: "A√s/mm²", min: 0 }],
    formula: "I²t ≤ k²S²; required S = I√t/k; maximum time = (kS/I)².", assumptions: ["Adiabatic short-duration heating", "Entered k value represents the actual conductor and insulation temperature limits"], warnings: [standardWarning], faqs: faq("cable short-circuit thermal check"), relatedTools: ["protective-conductor-size-calculator", "short-circuit-current-calculator", "cable-derating-factor-calculator"], relatedProducts: [{ label: "VIOX cable connection products", href: "https://viox.com/cable-lug/" }], keywords: ["cable short circuit withstand calculator", "i2t cable calculator", "adiabatic cable equation"]
  },
  {
    slug: "motor-starting-voltage-drop-calculator", title: "Motor Starting Voltage Drop Calculator", shortTitle: "Motor Start Drop", category: "motor-control",
    description: "Estimate bus voltage dip during motor starting from motor current, starting method, transformer impedance, and feeder impedance.", intent: "Screen DOL, star-delta, soft-starter, and VFD starting impact on a low-voltage bus.",
    fields: [{ id: "motorPower", label: "Motor output power", type: "number", defaultValue: 75, unit: "kW", min: 0 }, { id: "voltage", label: "Line voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "efficiency", label: "Motor efficiency", type: "number", defaultValue: 92, unit: "%", min: 1, max: 100 }, { id: "powerFactor", label: "Running power factor", type: "number", defaultValue: 0.86, min: 0.01, max: 1 }, { id: "method", label: "Starting method", type: "select", defaultValue: "dol", options: [{ value: "dol", label: "Direct-on-line" }, { value: "star-delta", label: "Star-delta" }, { value: "soft", label: "Soft starter" }, { value: "vfd", label: "VFD" }] }, { id: "dolMultiple", label: "DOL locked-rotor current", type: "number", defaultValue: 6, unit: "×FLC", min: 0 }, { id: "transformerKva", label: "Transformer rating", type: "number", defaultValue: 1000, unit: "kVA", min: 0 }, { id: "transformerZ", label: "Transformer impedance", type: "number", defaultValue: 6, unit: "%Z", min: 0 }, { id: "feederZ", label: "Feeder impedance per phase", type: "number", defaultValue: 0.01, unit: "Ω", min: 0 }],
    formula: "Starting current applies a method factor to DOL locked-rotor current; approximate dip = Istart×Zsource equivalent / phase voltage.", assumptions: ["Balanced three-phase motor", "Transformer and feeder impedance are represented mainly by their magnitudes", "Utility source upstream of the transformer is stiff"], warnings: [standardWarning, "A full study should use complex R+jX source, motor locked-rotor data, other running loads, and dynamic acceleration."], faqs: faq("motor-start voltage-dip estimate"), relatedTools: ["motor-current-calculator", "motor-starter-selection-calculator", "transformer-sizing-calculator"], relatedProducts: [{ label: "VIOX motor-control products", href: "https://viox.com/ac-contactor/" }], keywords: ["motor starting voltage drop calculator", "motor voltage dip", "dol starting current transformer"]
  },
  {
    slug: "vfd-sizing-protection-calculator", title: "VFD Sizing, Protection and Panel Calculator", shortTitle: "VFD Sizing", category: "motor-control",
    description: "Estimate the minimum VFD output-current class and screen input protection, bypass contactor, filtering, braking, and panel heat requirements.", intent: "Coordinate a variable frequency drive with VIOX circuit protection, contactors, SPD, wiring, and enclosure thermal design.",
    fields: [{ id: "motorPower", label: "Motor rated output power", type: "number", defaultValue: 30, unit: "kW", min: 0 }, { id: "motorVoltage", label: "Motor rated voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "motorCurrent", label: "Motor nameplate current", type: "number", defaultValue: 57, unit: "A", min: 0 }, { id: "motorEfficiency", label: "Motor efficiency", type: "number", defaultValue: 92, unit: "%", min: 1, max: 100 }, { id: "motorPowerFactor", label: "Motor power factor", type: "number", defaultValue: 0.86, min: 0.01, max: 1 }, { id: "loadType", label: "Application duty", type: "select", defaultValue: "constant", options: [{ value: "variable", label: "Variable torque: fan / centrifugal pump" }, { value: "constant", label: "Constant torque: conveyor / mixer" }, { value: "heavy", label: "Heavy or overhauling: hoist / crane" }] }, { id: "requiredOverload", label: "Required short-time overload", type: "number", defaultValue: 150, unit: "%", min: 100, max: 250 }, { id: "designMargin", label: "Additional sizing margin", type: "number", defaultValue: 10, unit: "%", min: 0, max: 50 }, { id: "supplyVoltage", label: "VFD supply voltage", type: "number", defaultValue: 400, unit: "V", min: 0 }, { id: "vfdEfficiency", label: "VFD efficiency at duty point", type: "number", defaultValue: 97, unit: "%", min: 80, max: 100 }, { id: "ambient", label: "Maximum panel ambient", type: "number", defaultValue: 40, unit: "°C" }, { id: "altitude", label: "Installation altitude", type: "number", defaultValue: 500, unit: "m", min: 0 }, { id: "motorCableLength", label: "VFD-to-motor cable length", type: "number", defaultValue: 40, unit: "m", min: 0 }, { id: "braking", label: "Rapid braking or overhauling load", type: "select", defaultValue: "no", options: [{ value: "no", label: "No" }, { value: "yes", label: "Yes" }] }, { id: "bypass", label: "Across-line bypass required", type: "select", defaultValue: "no", options: [{ value: "no", label: "No" }, { value: "yes", label: "Yes" }] }, { id: "faultCurrent", label: "Prospective short-circuit current", type: "number", defaultValue: 10, unit: "kA", min: 0 }, { id: "candidateBreaking", label: "Candidate protection breaking capacity", type: "number", defaultValue: 25, unit: "kA", min: 0 }],
    formula: "Imotor = Pout/(√3Vpfη); required VFD current = max(nameplate, calculated current) × design margin / environmental derating.", assumptions: ["Three-phase induction motor and PWM VFD", "Environmental derating is a screening sensitivity only", "VFD output-current rating, not kW alone, governs selection"], warnings: [standardWarning, "Final overload, ambient, altitude, cable-length, filter, braking, fuse, breaker, RCD, and SCCR selection must follow the exact VFD manufacturer manual."], faqs: [{ question: "Should VFD size follow motor kW or motor current?", answer: "Use the motor nameplate current and the VFD's continuous output-current rating for the selected duty. kW is a useful cross-check, not the sole selection basis." }, { question: "Does the input breaker provide motor overload protection?", answer: "Not by itself. The input protective device addresses short-circuit and feeder protection; motor thermal protection depends on the drive functions, motor data, and applicable rules." }, { question: "When is an output filter required?", answer: "It depends on cable length, switching frequency, motor insulation, voltage, grounding, and the VFD manual. The calculator only flags when a detailed filter review is warranted." }], relatedTools: ["motor-current-calculator", "circuit-breaker-size-calculator", "enclosure-temperature-rise-calculator"], relatedProducts: [{ label: "VIOX MCCB and motor-control products", href: "https://viox.com/mccb/" }, { label: "VIOX AC contactors", href: "https://viox.com/ac-contactor/" }], keywords: ["vfd sizing calculator", "vfd protection calculator", "variable frequency drive size", "vfd breaker size", "vfd panel heat"]
  },
  {
    slug: "arc-flash-incident-energy-calculator", title: "Arc Flash Incident Energy Calculator – IEEE 1584-2018", shortTitle: "Arc Flash", category: "circuit-protection",
    description: "Calculate IEEE 1584-2018 arcing current, incident energy, and arc-flash boundary for normal and reduced-current clearing-time scenarios.", intent: "Support qualified arc-flash study screening for three-phase AC equipment from 208 V to 15 kV without making PPE or energized-work decisions.",
    fields: [{ id: "voltage", label: "Three-phase open-circuit voltage", type: "number", defaultValue: 480, unit: "V", min: 208, max: 15000 }, { id: "faultCurrent", label: "Bolted three-phase fault current", type: "number", defaultValue: 20, unit: "kA", min: 0 }, { id: "electrode", label: "Electrode configuration", type: "select", defaultValue: "VCB", options: [{ value: "VCB", label: "VCB – Vertical conductors in box" }, { value: "VCBB", label: "VCBB – Vertical in box with barrier" }, { value: "HCB", label: "HCB – Horizontal conductors in box" }, { value: "VOA", label: "VOA – Vertical conductors in open air" }, { value: "HOA", label: "HOA – Horizontal conductors in open air" }] }, { id: "gap", label: "Conductor gap", type: "number", defaultValue: 32, unit: "mm", min: 0 }, { id: "workingDistance", label: "Working distance", type: "number", defaultValue: 610, unit: "mm", min: 305 }, { id: "width", label: "Enclosure width", type: "number", defaultValue: 508, unit: "mm", min: 0 }, { id: "height", label: "Enclosure height", type: "number", defaultValue: 508, unit: "mm", min: 0 }, { id: "depth", label: "Enclosure depth", type: "number", defaultValue: 508, unit: "mm", min: 0 }, { id: "normalTime", label: "Clearing time at normal arcing current", type: "number", defaultValue: 80, unit: "ms", min: 0 }, { id: "reducedTime", label: "Clearing time at reduced arcing current", type: "number", defaultValue: 120, unit: "ms", min: 0 }],
    formula: "IEEE 1584-2018 empirical models calculate Iarc at voltage anchor points, apply electrode and enclosure corrections, interpolate to system voltage, and repeat with Iarc,min = Iarc(1 − 0.5VarCf).", assumptions: ["Three-phase 50/60 Hz AC system within the IEEE 1584-2018 model range", "Bolted fault current comes from a current short-circuit study", "Each clearing time includes relay sensing, intentional delay, breaker mechanism, and interruption time at the calculated arcing current"], warnings: ["This calculator does not replace a site-specific arc-flash study, protective-device coordination study, equipment inspection, or qualified electrical safety assessment.", "IEEE 1584 does not recommend PPE or determine whether energized work is justified. Do not convert the result automatically into a PPE category.", "Use the exact protective-device curve at both displayed arcing currents; a reduced current can produce a longer clearing time and higher incident energy."], faqs: [{ question: "Why are two clearing times required?", answer: "IEEE 1584-2018 evaluates normal and reduced arcing current. The reduced current can move a breaker or fuse into a slower part of its time-current curve, producing the worst incident energy." }, { question: "Does a result below 1.2 cal/cm² mean the work is safe?", answer: "No. It only describes predicted thermal incident energy at the entered distance. Shock, arc likelihood, equipment condition, task risk, maintenance, and work-practice requirements remain separate." }, { question: "Can this calculate single-phase or DC arc flash?", answer: "No. IEEE 1584-2018 covers three-phase AC equipment from 208 V to 15 kV. Single-phase and DC systems require other methods." }], relatedTools: ["short-circuit-current-calculator", "breaker-selectivity-calculator", "cable-short-circuit-thermal-calculator"], relatedProducts: [{ label: "VIOX MCCB and ACB protection", href: "https://viox.com/mccb/" }], keywords: ["arc flash calculator", "ieee 1584 calculator", "incident energy calculator", "arc flash boundary calculator"]
  }
];
