import type { ToolEquation, ToolEquationSymbol } from "./types";

const make = (title: string, intro: string, expressions: string[], symbols: ToolEquationSymbol[], conclusion: string): ToolEquation => ({ title, intro, equations: expressions.map((expression) => ({ expression })), symbols, conclusion });

export const expansionEquations: Record<string, ToolEquation> = {
  "rc-circuit-time-constant-calculator": make("RC time constant and filter equations", "An ideal first-order RC network links timing and cutoff frequency through the same product RC.", ["τ = R × C", "fc = 1/(2πRC)", "Vcharge = Vs(1 − e^(−t/τ))", "Vdischarge = V0e^(−t/τ)", "XC = 1/(2πfC)"], [{ symbol: "τ", meaning: "Time constant", unit: "s" }, { symbol: "fc", meaning: "First-order cutoff frequency", unit: "Hz" }, { symbol: "XC", meaning: "Capacitive reactance", unit: "Ω" }], "Real capacitors add tolerance, leakage, ESR and parasitic inductance."),
  "rlc-impedance-resonance-calculator": make("RLC impedance and resonance equations", "Series circuits combine impedance while parallel circuits combine admittance.", ["XL = 2πfL", "XC = 1/(2πfC)", "Zseries = R + j(XL − XC)", "Yparallel = 1/R + j(1/XC − 1/XL)", "f0 = 1/(2π√LC)"], [{ symbol: "XL", meaning: "Inductive reactance", unit: "Ω" }, { symbol: "XC", meaning: "Capacitive reactance", unit: "Ω" }, { symbol: "f0", meaning: "Ideal resonance frequency", unit: "Hz" }], "Losses and parasitics determine real resonance magnitude and Q."),
  "current-divider-calculator": make("Current-divider equations", "Parallel resistive branches share one voltage and split current according to conductance.", ["Req = 1/Σ(1/Rn)", "In = Itotal × Req/Rn", "V = Itotal × Req", "Pn = In²Rn"], [{ symbol: "Req", meaning: "Equivalent parallel resistance", unit: "Ω" }, { symbol: "In", meaning: "Current in branch n", unit: "A" }], "Reactive branches require complex impedance and phasor analysis."),
  "capacitor-reactance-energy-calculator": make("Capacitor reactance and energy equations", "Capacitance determines AC reactance and electrostatic energy at the entered operating point.", ["XC = 1/(2πfC)", "I = V/XC", "E = ½CV²", "Q = CV", "Cseries = C1C2/(C1+C2)"], [{ symbol: "C", meaning: "Capacitance", unit: "F" }, { symbol: "E", meaning: "Stored energy", unit: "J" }, { symbol: "Q", meaning: "Stored charge", unit: "C" }], "Real capacitor selection requires voltage, ESR, ripple and temperature checks."),
  "inductor-reactance-energy-calculator": make("Inductor reactance and energy equations", "Inductance determines AC reactance, magnetic energy, and an ideal R-L time constant.", ["XL = 2πfL", "|Z| = √(R²+XL²)", "I = V/|Z|", "E = ½LI²", "τ = L/R"], [{ symbol: "L", meaning: "Inductance", unit: "H" }, { symbol: "E", meaning: "Stored magnetic energy", unit: "J" }, { symbol: "τ", meaning: "R-L time constant", unit: "s" }], "Saturation and core loss require real component data."),
  "current-shunt-calculator": make("DC current-shunt equations", "A calibrated shunt converts current into a small measurable voltage while dissipating I²R heat.", ["Rshunt = Vrated/Irated", "Vactual = IactualRshunt", "P = I²Rshunt"], [{ symbol: "Rshunt", meaning: "Calibrated shunt resistance", unit: "Ω" }, { symbol: "Vactual", meaning: "Shunt output voltage", unit: "V" }], "Kelvin sensing and temperature coefficient govern accuracy."),
  "emergency-lighting-battery-calculator": make("Emergency-lighting battery energy equations", "Fixture load energy is corrected for conversion loss, usable discharge, aging, temperature, and margin.", ["Eload = Pfixture × N × t", "Ebattery = Eload × (1+margin)/(η × DOD × Faging × Ftemp)", "Ah = Ebattery/Vbattery"], [{ symbol: "Eload", meaning: "Energy delivered to emergency fixtures", unit: "Wh" }, { symbol: "Ah", meaning: "Required nominal battery capacity", unit: "Ah" }], "Battery energy does not prove emergency illuminance or legal compliance."),
  "lighting-circuit-load-calculator": make("Lighting circuit load equations", "Fixture input watts and driver power factor determine steady VA and current; inrush is screened separately.", ["P = Pfixture × N", "S = P/PF", "I = S/V", "Ncircuits = ceil(I/(In × Fload))", "Iinrush = Ifixture,inrush × N × Fsim"], [{ symbol: "S", meaning: "Lighting apparent power", unit: "VA" }, { symbol: "In", meaning: "Breaker rated current", unit: "A" }], "Use the driver manufacturer's protective-device compatibility table for final circuit quantity."),
  "branch-circuit-count-calculator": make("Branch-circuit planning equations", "General load is divided by planned usable VA per circuit before mandatory and dedicated circuits are added.", ["Ngeneral = ceil(Pgeneral/(V × In × Fload))", "Ntotal = Ngeneral + Nmandatory + Ndedicated"], [{ symbol: "Fload", meaning: "Planned maximum circuit-loading fraction" }, { symbol: "Nmandatory", meaning: "Entered jurisdiction-specific required circuits" }], "The final panel schedule must follow the adopted code and actual equipment plan."),
  "electrical-panel-load-spare-capacity-calculator": make("Panel load and spare-capacity equations", "Demand power is converted to current before comparing with the entered panel main rating.", ["Pdemand = Pconnected × Fdemand", "I3φ = 1000P/(√3VPF)", "I1φ = 1000P/(VPF)", "Ispare = Imain − Idemand", "Unbalance% = max|Iphase−Iavg|/Iavg × 100"], [{ symbol: "Fdemand", meaning: "Entered demand factor" }, { symbol: "Ispare", meaning: "Arithmetic spare-current screen", unit: "A" }], "Positive arithmetic spare does not by itself approve added load."),
  "transformer-impedance-calculator": make("Transformer impedance equations", "Nameplate percent impedance is converted to ohms on the transformer rating base before resolving resistance and reactance.", ["Ifl = S/(√3V) for three-phase", "Zbase = V²/S", "|Z| = Zbase × %Z/100", "R = |Z|/√(1+(X/R)²)", "X = R × X/R", "Isc = Ifl × 100/%Z"], [{ symbol: "S", meaning: "Transformer apparent-power rating", unit: "VA" }, { symbol: "V", meaning: "Rated secondary voltage", unit: "V" }, { symbol: "%Z", meaning: "Nameplate percent impedance" }, { symbol: "Isc", meaning: "Infinite-bus symmetrical fault current", unit: "A" }], "Add source and conductor impedance for a location-specific result."),
  "generator-sizing-calculator": make("Generator sizing method", "The larger of steady-state design load and the entered starting step is corrected for generic site derating.", ["Psteady = Prun × Freserve × Fgrowth", "Pstep = Prun + Pstarting", "Pdesign = max(Psteady, Pstep)", "Srated = Pdesign/(PF × Kalt × Ktemp)"], [{ symbol: "Pdesign", meaning: "Required site active-power output", unit: "kW" }, { symbol: "PF", meaning: "Load power factor" }, { symbol: "Kalt", meaning: "Altitude output factor" }, { symbol: "Ktemp", meaning: "Ambient-temperature output factor" }], "Manufacturer transient and site-rating data govern final selection."),
  "harmonic-thd-calculator": make("Harmonic and THD equations", "Orthogonal RMS harmonic components combine by root-sum-square.", ["THD = √(Σh>1 Xh²)/X1 × 100%", "Xrms = √(Σh≥1 Xh²)", "Xtriplen = √(X3² + X9² + ...)"], [{ symbol: "X1", meaning: "Fundamental RMS magnitude" }, { symbol: "Xh", meaning: "RMS magnitude of harmonic order h" }, { symbol: "THD", meaning: "Total harmonic distortion relative to the fundamental", unit: "%" }], "IEEE 519 compliance requires PCC and system-ratio data beyond THD."),
  "ups-backup-time-calculator": make("UPS energy-method runtime equations", "Nominal battery energy is reduced by UPS efficiency, remaining capacity, and permitted depth of discharge.", ["Enom = Vbattery × Ns × Ah × Np", "Eusable = Enom × η × Faging × DOD", "t = Eusable/Pload", "IDC = Pload/(Vbank × η)"], [{ symbol: "Ns", meaning: "Series battery count" }, { symbol: "Np", meaning: "Parallel string count" }, { symbol: "η", meaning: "UPS efficiency" }, { symbol: "t", meaning: "Energy-method runtime", unit: "h" }], "Use manufacturer constant-power discharge tables for final runtime."),
  "inverter-sizing-calculator": make("Inverter sizing equations", "Continuous active power, load power factor, DC voltage, efficiency, and PV ratio are evaluated separately.", ["Pinv = Pload × (1+margin)", "Sinv = Pinv/PF", "IDC = 1000Pinv/(VDC × η)", "PPV = Pinv × DC/AC ratio"], [{ symbol: "Pinv", meaning: "Continuous inverter active-power reference", unit: "kW" }, { symbol: "Sinv", meaning: "Continuous apparent-power reference", unit: "kVA" }, { symbol: "IDC", meaning: "Nominal DC input current", unit: "A" }], "Recalculate DC current at minimum operating voltage."),
  "grounding-resistance-calculator": make("Vertical ground-rod resistance equations", "A uniform-soil approximation estimates one rod before applying a generic multiple-rod spacing efficiency.", ["R1 = ρ/(2πL) × [ln(4L/d) − 1]", "Rn ≈ R1/(n × ηspacing)"], [{ symbol: "ρ", meaning: "Uniform soil resistivity", unit: "Ω·m" }, { symbol: "L", meaning: "Buried rod length", unit: "m" }, { symbol: "d", meaning: "Rod diameter", unit: "m" }, { symbol: "ηspacing", meaning: "Generic rod-array efficiency" }], "Field measurement and layered-soil analysis govern final grounding performance."),
  "insulation-resistance-temperature-correction-calculator": make("Insulation-resistance temperature correction", "The generic doubling rule normalizes comparable readings to a chosen reference temperature.", ["Rref = Rmeasured × 2^((Tmeasured − Tref)/ΔTdouble)"], [{ symbol: "Rref", meaning: "Resistance corrected to reference temperature", unit: "MΩ" }, { symbol: "ΔTdouble", meaning: "Temperature interval corresponding to a resistance doubling", unit: "°C" }], "Use the exact insulation or equipment correction curve when available."),
  "cable-pulling-tension-calculator": make("Cable pulling tension equations", "A straight section is followed by an equivalent bend using the capstan relationship.", ["Tstraight = T0 + μwLg", "Tout = Tstraight × e^(μθ)", "SWP = Tout/r"], [{ symbol: "μ", meaning: "Coefficient of friction" }, { symbol: "w", meaning: "Cable mass per unit length", unit: "kg/m" }, { symbol: "θ", meaning: "Bend angle", unit: "rad" }, { symbol: "r", meaning: "Bend radius", unit: "m" }], "Real routes require segment-by-segment calculation in pulling direction."),
  "motor-torque-calculator": make("Motor torque equations", "Shaft output power and rotational speed define steady operating torque.", ["T(N·m) = 9550 × Pout(kW)/n(rpm)", "Pout = Pin × η", "T(lb-ft) = 5252 × Pout(hp)/n(rpm)"], [{ symbol: "T", meaning: "Shaft torque" }, { symbol: "Pout", meaning: "Mechanical shaft output power" }, { symbol: "n", meaning: "Shaft speed", unit: "rpm" }], "Starting and breakdown torque require the motor torque-speed curve."),
  "motor-control-panel-load-calculator": make("Motor control panel feeder equations", "The preliminary feeder basis combines 125% of the largest motor with remaining motor and non-motor load.", ["Ibase = 1.25Ilargest + Iother × Fdemand + 1000Snonmotor/(√3V)", "Idesign = Ibase × (1+Fspare)"], [{ symbol: "Ilargest", meaning: "Largest motor full-load current", unit: "A" }, { symbol: "Iother", meaning: "Sum of remaining motor currents", unit: "A" }, { symbol: "Snonmotor", meaning: "Balanced non-motor load", unit: "kVA" }], "Verify the adopted motor-feeder rule and complete assembly SCCR."),
  "battery-capacity-converter": make("Battery capacity conversion equations", "Series units increase pack voltage, while parallel strings increase ampere-hour capacity.", ["Vpack = Vunit × Ns", "Cpack = Cunit × Np", "Enominal = Vpack × Cpack", "Eusable = Enominal × DOD × η"], [{ symbol: "Vpack", meaning: "Nominal pack voltage", unit: "V" }, { symbol: "Cpack", meaning: "Nominal pack capacity", unit: "Ah" }, { symbol: "Ns", meaning: "Number of units connected in series" }, { symbol: "Np", meaning: "Number of parallel strings" }, { symbol: "Enominal", meaning: "Nominal battery energy", unit: "Wh" }, { symbol: "DOD", meaning: "Permitted depth of discharge" }, { symbol: "η", meaning: "Discharge-system efficiency" }], "Nameplate capacity varies with chemistry, temperature, age, and discharge rate, so this is an energy conversion rather than a battery qualification."),
  "power-energy-time-calculator": make("Power, energy, and time equations", "Power is the rate of energy transfer. Any two quantities determine the third after conversion to compatible units.", ["E = P × t", "P = E / t", "t = E / P", "1 Wh = 3600 J"], [{ symbol: "E", meaning: "Energy", unit: "J or Wh" }, { symbol: "P", meaning: "Average active power", unit: "W" }, { symbol: "t", meaning: "Operating duration", unit: "s or h" }], "Power must represent the relevant time average; peak power cannot be used as average energy consumption without a load profile."),
  "voltage-divider-calculator": make("Voltage divider equations", "An unloaded divider uses two series resistors. A connected load appears in parallel with the lower resistor.", ["Vout = Vin × R2 / (R1 + R2)", "Rlower = R2 ∥ RL = R2 × RL / (R2 + RL)", "Vout,loaded = Vin × Rlower / (R1 + Rlower)", "P = I²R"], [{ symbol: "Vin", meaning: "Divider input voltage", unit: "V" }, { symbol: "Vout", meaning: "Divider output voltage", unit: "V" }, { symbol: "R1", meaning: "Upper resistor", unit: "Ω" }, { symbol: "R2", meaning: "Lower resistor", unit: "Ω" }, { symbol: "RL", meaning: "Connected load resistance", unit: "Ω" }, { symbol: "Rlower", meaning: "Effective loaded lower resistance", unit: "Ω" }], "A voltage divider is suitable for signal scaling, but it is not a regulated supply and its output changes with load current."),
  "clearance-creepage-calculator": make("Clearance and creepage selection method", "IEC 60664-1 selects clearance and creepage from different electrical and environmental inputs; neither distance is calculated from one universal algebraic formula.", ["Clearance = f(Uimp, field, altitude, insulation)", "Creepage = f(Uworking, pollution degree, CTI group, insulation)", "daltitude = dtable × Kaltitude", "dreinforced,creepage = 2 × dbasic,creepage"], [{ symbol: "Uimp", meaning: "Rated impulse withstand voltage", unit: "kV" }, { symbol: "Uworking", meaning: "Highest working RMS or DC voltage across the insulation", unit: "V" }, { symbol: "CTI", meaning: "Comparative tracking index of the insulating material" }, { symbol: "Kaltitude", meaning: "Altitude correction factor above the reference altitude" }, { symbol: "dtable", meaning: "Distance selected from the applicable standard table", unit: "mm" }], "The lookup result is limited to the stated IEC 60664-1 conditions. Product standards and construction details can require larger distances or additional tests."),
  "pcb-conductor-spacing-calculator": make("PCB conductor spacing method", "PCB conductor spacing is selected from the voltage band and construction category. IPC voltage is DC or AC peak, so RMS AC input is converted before the lookup.", ["Vpeak = √2 × Vrms", "Vlookup = VDC or Vpeak", "d = dtable for Vlookup ≤ 500 V", "d = d500 + k × (Vlookup − 500) for Vlookup > 500 V", "ddesign = d × (1 + margin)"], [{ symbol: "Vpeak", meaning: "Peak value of an AC voltage difference", unit: "V" }, { symbol: "Vrms", meaning: "RMS value of the AC voltage difference", unit: "V" }, { symbol: "dtable", meaning: "Legacy table spacing for the selected voltage band and conductor category", unit: "mm" }, { symbol: "d500", meaning: "Spacing at the 301–500 V band", unit: "mm" }, { symbol: "k", meaning: "Additional spacing per volt above 500 V", unit: "mm/V" }, { symbol: "ddesign", meaning: "Spacing after the user-entered design margin", unit: "mm" }], "The lookup is a PCB layout reference based on publicly verifiable IPC-2221B values. Verify IPC-2221C and the applicable product-safety standard before design release."),
  "three-phase-power-calculator": {
    title: "Three-phase power equations",
    intro: "For a balanced three-phase system, line-to-line voltage and line current define apparent power. Power factor then separates apparent power into active and reactive components.",
    equations: [
      {
        label: "Apparent power",
        expression: "S = √3 × VLL × I / 1000",
        mathml: `<math display="block" aria-label="S equals square root of three times V L L times I divided by one thousand"><mi>S</mi><mo>=</mo><mfrac><mrow><msqrt><mn>3</mn></msqrt><msub><mi>V</mi><mrow><mi>L</mi><mi>L</mi></mrow></msub><mi>I</mi></mrow><mn>1000</mn></mfrac></math>`
      },
      {
        label: "Active power",
        expression: "P = S × PF",
        mathml: `<math display="block" aria-label="P equals S times power factor"><mi>P</mi><mo>=</mo><mi>S</mi><mo>×</mo><mi>PF</mi></math>`
      },
      {
        label: "Reactive power",
        expression: "Q = ±√(S² − P²)",
        mathml: `<math display="block" aria-label="Q equals plus or minus square root of S squared minus P squared"><mi>Q</mi><mo>=</mo><mo>±</mo><msqrt><mrow><msup><mi>S</mi><mn>2</mn></msup><mo>−</mo><msup><mi>P</mi><mn>2</mn></msup></mrow></msqrt></math>`
      },
      {
        label: "Current from active power",
        expression: "I = 1000 × P / (√3 × VLL × PF)",
        mathml: `<math display="block" aria-label="I equals one thousand times P divided by square root of three times V L L times power factor"><mi>I</mi><mo>=</mo><mfrac><mrow><mn>1000</mn><mi>P</mi></mrow><mrow><msqrt><mn>3</mn></msqrt><msub><mi>V</mi><mrow><mi>L</mi><mi>L</mi></mrow></msub><mi>PF</mi></mrow></mfrac></math>`
      },
      {
        label: "Current from apparent power",
        expression: "I = 1000 × S / (√3 × VLL)",
        mathml: `<math display="block" aria-label="I equals one thousand times S divided by square root of three times V L L"><mi>I</mi><mo>=</mo><mfrac><mrow><mn>1000</mn><mi>S</mi></mrow><mrow><msqrt><mn>3</mn></msqrt><msub><mi>V</mi><mrow><mi>L</mi><mi>L</mi></mrow></msub></mrow></mfrac></math>`
      }
    ],
    symbols: [
      { symbol: "S", meaning: "Apparent power", unit: "kVA" },
      { symbol: "P", meaning: "Active power", unit: "kW" },
      { symbol: "Q", meaning: "Reactive power; positive for lagging loads and negative for leading loads", unit: "kvar" },
      { symbol: "VLL", meaning: "RMS line-to-line voltage", unit: "V" },
      { symbol: "I", meaning: "RMS line current", unit: "A" },
      { symbol: "PF", meaning: "Power factor, equal to cos φ" },
      { symbol: "φ", meaning: "Phase angle between voltage and current", unit: "°" }
    ],
    conclusion: "The factor 1000 converts VA to kVA or W to kW. These equations assume a balanced sinusoidal three-phase system; unbalanced or harmonic-rich loads require per-phase measurements and true-power analysis."
  },
  "ohms-law-calculator": make("Ohm's law equations", "Voltage, current, resistance, and power describe one resistive operating point.", ["V = I × R", "P = V × I = I² × R = V² / R"], [{ symbol: "V", meaning: "Voltage", unit: "V" }, { symbol: "I", meaning: "Current", unit: "A" }, { symbol: "R", meaning: "Resistance", unit: "Ω" }, { symbol: "P", meaning: "Electrical power", unit: "W" }], "These relationships apply directly to DC and ideal resistive loads."),
  "watts-amps-volts-calculator": make("Watts, amps, and volts equations", "The current equation changes with the phase arrangement.", ["DC: P = V × I", "Single-phase: P = V × I × pf", "Three-phase: P = √3 × VLL × I × pf"], [{ symbol: "P", meaning: "Active power", unit: "W" }, { symbol: "V", meaning: "DC or single-phase voltage", unit: "V" }, { symbol: "VLL", meaning: "Three-phase line-to-line voltage", unit: "V" }, { symbol: "I", meaning: "Line current", unit: "A" }, { symbol: "pf", meaning: "Power factor" }], "Use line-to-line voltage for a balanced three-phase load."),
  "ev-charging-time-cost-calculator": make("EV charging time and cost equations", "The battery receives less energy than the supply delivers because charging is not perfectly efficient.", ["Ebatt = C × (SOCtarget − SOCstart)", "Ewall = Ebatt / η", "t = Ewall / Pcharger", "Cost = Ewall × tariff"], [{ symbol: "C", meaning: "Usable battery capacity", unit: "kWh" }, { symbol: "SOC", meaning: "State of charge" }, { symbol: "η", meaning: "Charging efficiency" }, { symbol: "t", meaning: "Charging time", unit: "h" }], "Actual time can be longer when the vehicle tapers charging power."),
  "battery-charging-time-calculator": make("Battery charging time equation", "Required capacity is divided by the effective average charging rate.", ["t = C × ΔSOC / (rate × η)"], [{ symbol: "t", meaning: "Charging time", unit: "h" }, { symbol: "C", meaning: "Battery capacity in Ah or kWh" }, { symbol: "ΔSOC", meaning: "Target minus starting state of charge" }, { symbol: "η", meaning: "Charging efficiency" }], "Use average current or power over the complete charging period."),
  "resistor-series-parallel-calculator": make("Series and parallel resistance equations", "Series resistances add directly; parallel conductances add.", ["Series: Req = R1 + R2 + … + Rn", "Parallel: 1 / Req = 1/R1 + 1/R2 + … + 1/Rn"], [{ symbol: "Req", meaning: "Equivalent resistance", unit: "Ω" }, { symbol: "Rn", meaning: "Individual resistor value", unit: "Ω" }], "Power and voltage ratings must be checked for every individual resistor."),
  "electrical-unit-converter": make("Electrical unit conversion method", "Power values are converted through watts, energy values through joules, and phase current uses the selected supply arrangement.", ["Pto = Pfrom × Kfrom / Kto", "Eto = Efrom × Kfrom / Kto", "Single-phase: I = P / (V × pf)", "Three-phase: I = P / (√3 × VLL × pf)"], [{ symbol: "K", meaning: "Unit-to-base conversion factor" }, { symbol: "P", meaning: "Active power", unit: "W" }, { symbol: "E", meaning: "Energy", unit: "J" }, { symbol: "I", meaning: "Current", unit: "A" }, { symbol: "VLL", meaning: "Line-to-line voltage", unit: "V" }, { symbol: "pf", meaning: "Power factor" }], "Power cannot be converted to energy without adding a duration."),
  "contactor-selection-calculator": make("Contactor load-current equation", "Three-phase motor input current is calculated before applying a duty margin and utilization category.", ["I = Pout / (√3 × VLL × pf × η)", "Iselection = I × Fduty"], [{ symbol: "I", meaning: "Estimated load current", unit: "A" }, { symbol: "Pout", meaning: "Motor output power", unit: "W" }, { symbol: "η", meaning: "Motor efficiency" }, { symbol: "Fduty", meaning: "Preliminary operating-duty margin" }], "Final AC-1 or AC-3 selection uses the exact manufacturer voltage and kW table."),
  "breaker-selectivity-calculator": make("Breaker coordination screening", "The generic screen compares current ratings, B/C/D magnetic bands, and breaking capacity.", ["Rrating = In,up / In,down", "Imagnetic = kcurve × In", "Icn ≥ Ik"], [{ symbol: "In", meaning: "Breaker rated current", unit: "A" }, { symbol: "kcurve", meaning: "Generic magnetic-trip multiple" }, { symbol: "Icn", meaning: "Breaking capacity", unit: "kA" }, { symbol: "Ik", meaning: "Prospective fault current", unit: "kA" }], "Only a manufacturer selectivity or cascading table can confirm the exact paired devices."),
  "lightning-risk-assessment-calculator": make("Simplified lightning exposure equations", "Building dimensions define an equivalent collection area, which is combined with an approximate ground flash density.", ["Ae = L × W + 6H(L + W) + 9πH²", "Ng ≈ 0.04 × Td^1.25", "Nd = Ng × Ae × 10⁻⁶ × Cd"], [{ symbol: "Ae", meaning: "Equivalent collection area", unit: "m²" }, { symbol: "Td", meaning: "Thunderstorm days per year" }, { symbol: "Ng", meaning: "Estimated ground flash density", unit: "km⁻² year⁻¹" }, { symbol: "Cd", meaning: "Relative location factor" }], "This is an exposure screen, not the complete IEC 62305-2 component-risk calculation."),
  "enclosure-temperature-rise-calculator": make("Enclosure cooling and heat-balance equations", "The calculator balances internal component losses, an entered outdoor solar allowance, wall heat transfer, and open-loop airflow at steady state.", ["Qgenerated = Qinternal + Qsolar", "Qwall = Ueff × Aeff × (Tambient − Ttarget)", "Qactive = max(0, Qgenerated + Qwall)", "qv = Qactive × Fmargin / (0.33 × (Ttarget − Tambient))", "Tinside = Tambient + Qgenerated / (Ueff × Aeff + 0.33 × qv)", "Kheat-exchanger = Qactive × Fmargin / (Ttarget − Tambient)"], [{ symbol: "Qgenerated", meaning: "Total heat generated or absorbed by the enclosure", unit: "W" }, { symbol: "Qinternal", meaning: "Component losses released as heat inside the enclosure", unit: "W" }, { symbol: "Qsolar", meaning: "User-entered outdoor solar heat allowance", unit: "W" }, { symbol: "Qwall", meaning: "Heat entering through the wall; negative when the wall passively rejects heat", unit: "W" }, { symbol: "Ueff", meaning: "Effective overall heat-transfer coefficient including entered insulation", unit: "W/m²K" }, { symbol: "Aeff", meaning: "Exposed enclosure surface area", unit: "m²" }, { symbol: "qv", meaning: "Delivered open-loop airflow", unit: "m³/h" }, { symbol: "Fmargin", meaning: "Entered cooling design-margin multiplier" }, { symbol: "Kheat-exchanger", meaning: "Required closed-loop heat-exchanger performance reference", unit: "W/K" }], "Open-loop ventilation cannot cool below ambient temperature. Manufacturer performance curves, pressure loss, enclosure rating, condensation, hot spots, and applicable thermal standards govern final equipment selection."),
  "panel-heat-loss-calculator": make("Panel heat-loss total", "Only losses dissipated inside the enclosure contribute to the entered thermal load.", ["Pheat = Fsim × Σ(Pcomponent)"], [{ symbol: "Pheat", meaning: "Simultaneous internal heat load", unit: "W" }, { symbol: "Fsim", meaning: "Simultaneous heat factor" }, { symbol: "Pcomponent", meaning: "Individual component power loss", unit: "W" }], "Use manufacturer watt-loss data at the expected operating point."),
  "pv-string-sizing-calculator": make("PV string voltage equations", "Cold temperature raises module open-circuit voltage while hot temperature lowers operating voltage.", ["V(T) = VSTC × [1 + β × (T − 25°C)]", "Nmax = floor(VDC,max / Voc,cold)", "Nmin = ceil(VMPPT,min / Vmpp,hot)"], [{ symbol: "β", meaning: "Module voltage temperature coefficient", unit: "/°C" }, { symbol: "N", meaning: "Modules connected in series" }, { symbol: "Voc", meaning: "Module open-circuit voltage", unit: "V" }, { symbol: "Vmpp", meaning: "Module maximum-power voltage", unit: "V" }], "Both the inverter absolute maximum and MPPT window must be satisfied."),
  "off-grid-solar-system-calculator": make("Off-grid solar sizing equations", "Daily energy determines array energy, battery autonomy, and inverter starting capacity separately.", ["PPV = Edaily / (Hsun × ηsystem)", "Ebattery = Edaily × Dautonomy / (DOD × ηbattery)", "Cbat = 1000 × Ebattery / Vsystem"], [{ symbol: "PPV", meaning: "Required PV array power", unit: "kWp" }, { symbol: "Edaily", meaning: "Daily load energy", unit: "kWh/day" }, { symbol: "Hsun", meaning: "Peak sun hours", unit: "h/day" }, { symbol: "DOD", meaning: "Allowed depth of discharge" }], "Seasonal hourly simulation is required for a firm system design."),
  "spd-backup-fuse-calculator": make("SPD backup-protection rules", "Backup protection must follow the exact SPD datasheet and withstand the installation fault current.", ["In,backup ≤ In,backup,max(SPD)", "Icn,backup ≥ Ik"], [{ symbol: "In,backup", meaning: "Backup fuse or breaker rating", unit: "A" }, { symbol: "Icn,backup", meaning: "Backup device breaking capacity", unit: "kA" }, { symbol: "Ik", meaning: "Prospective short-circuit current", unit: "kA" }], "A generic device is not interchangeable with the manufacturer-approved backup device."),
  "earth-fault-loop-impedance-calculator": make("Earth fault loop impedance equations", "The complete loop is compared with the maximum that produces the required protective-device operating current.", ["Zs = Ze + Ft × (R1 + R2)", "Zs,max = U0 / Ia", "If = U0 / Zs"], [{ symbol: "Zs", meaning: "Earth fault loop impedance", unit: "Ω" }, { symbol: "Ze", meaning: "External loop impedance", unit: "Ω" }, { symbol: "Ia", meaning: "Current causing operation in the required time", unit: "A" }, { symbol: "U0", meaning: "Nominal voltage to earth", unit: "V" }], "Use the current local table or exact device curve for the required disconnection time."),
  "cable-derating-factor-calculator": make("Cable derating equation", "Independent correction factors multiply the reference ampacity.", ["Iz,corrected = Iz,reference × Ca × Cg × Ci × Cs"], [{ symbol: "Iz", meaning: "Cable current-carrying capacity", unit: "A" }, { symbol: "Ca", meaning: "Ambient-temperature factor" }, { symbol: "Cg", meaning: "Grouping factor" }, { symbol: "Ci", meaning: "Installation factor" }, { symbol: "Cs", meaning: "Soil thermal factor" }], "Replace screening factors with values from the adopted installation table."),
  "maximum-demand-calculator": make("Maximum demand equations", "Category demand is calculated first and the overall simultaneity factor is then applied.", ["Pcategory = Pconnected × Fdemand", "Pmax = Fsim × Σ(Pcategory)", "I = Pmax / (√3 × VLL × pf)"], [{ symbol: "Pmax", meaning: "Maximum simultaneous active power", unit: "kW" }, { symbol: "Fdemand", meaning: "Category demand factor" }, { symbol: "Fsim", meaning: "Overall simultaneity factor" }], "Demand factors should come from project criteria, measured data, or applicable guidance."),
  "protective-conductor-size-calculator": make("Protective conductor adiabatic equation", "The PE conductor must withstand fault energy until the protective device clears.", ["Smin = I × √t / k", "I²t ≤ k²S²"], [{ symbol: "S", meaning: "Protective conductor cross-section", unit: "mm²" }, { symbol: "I", meaning: "Earth fault current", unit: "A" }, { symbol: "t", meaning: "Clearing time", unit: "s" }, { symbol: "k", meaning: "Material and insulation thermal constant", unit: "A√s/mm²" }], "Mechanical minimums and fault-loop requirements are separate checks."),
  "cable-short-circuit-thermal-calculator": make("Cable short-circuit thermal equation", "The same adiabatic relationship can check required area, maximum time, or withstand energy.", ["I²t ≤ k²S²", "Smin = I × √t / k", "tmax = (kS / I)²"], [{ symbol: "I", meaning: "Short-circuit current", unit: "A" }, { symbol: "t", meaning: "Fault duration", unit: "s" }, { symbol: "S", meaning: "Conductor cross-section", unit: "mm²" }, { symbol: "k", meaning: "Conductor and insulation constant", unit: "A√s/mm²" }], "Use the exact protective-device clearing time at the calculated fault current."),
  "motor-starting-voltage-drop-calculator": make("Motor starting voltage-drop equations", "Starting method changes the locked-rotor current applied to the source impedance.", ["IFLC = Pout / (√3 × VLL × pf × η)", "Istart = IFLC × KLRC × Kmethod", "ΔV% ≈ Istart × |Zsource| / Vphase × 100"], [{ symbol: "IFLC", meaning: "Motor full-load current", unit: "A" }, { symbol: "KLRC", meaning: "DOL locked-rotor current multiple" }, { symbol: "Kmethod", meaning: "Starting-method current factor" }, { symbol: "Zsource", meaning: "Transformer plus feeder impedance magnitude", unit: "Ω" }], "Critical systems need a complex-impedance dynamic motor-start study."),
  "vfd-sizing-protection-calculator": make("VFD current and panel equations", "VFD selection starts with motor nameplate current, optional service-factor loading, duty, environmental derating, and the drive manufacturer's output-current table.", ["Imotor = Pout / (√3 × VLL × pf × ηmotor)", "IVFD,min = max(Inameplate, Imotor) × FSF × Fduty × Fmargin / (Ftemp × Falt)", "Ploss,VFD ≈ Pmotor,input × (1/ηVFD − 1)"], [{ symbol: "IVFD,min", meaning: "Minimum continuous VFD output-current rating", unit: "A" }, { symbol: "FSF", meaning: "Service factor when above-nameplate operation is intentionally included" }, { symbol: "Fduty", meaning: "Application-duty screening factor" }, { symbol: "Ftemp", meaning: "Ambient-temperature derating factor" }, { symbol: "Falt", meaning: "Altitude derating factor" }, { symbol: "Ploss,VFD", meaning: "Estimated heat dissipated by the VFD", unit: "W" }], "Replace every generic factor with the exact VFD manufacturer's normal-duty or heavy-duty table before selection."),
  "arc-flash-incident-energy-calculator": make("IEEE 1584-2018 arc-flash calculation", "The empirical model calculates arcing current at voltage anchor points, applies geometry and enclosure corrections, then repeats the energy calculation for reduced arcing current.", ["Iarc,min = Iarc × (1 − 0.5 × VarCf)", "E = IEEE1584(Voc, Ibf, Iarc, G, D, EC, CF, t)", "AFB: E(AFB) = 1.2 cal/cm²"], [{ symbol: "Iarc", meaning: "Predicted normal arcing current", unit: "kA" }, { symbol: "Iarc,min", meaning: "Reduced arcing current used for the second clearing-time scenario", unit: "kA" }, { symbol: "Ibf", meaning: "Bolted three-phase fault current", unit: "kA" }, { symbol: "G", meaning: "Conductor gap", unit: "mm" }, { symbol: "D", meaning: "Working distance", unit: "mm" }, { symbol: "EC", meaning: "Electrode configuration" }, { symbol: "CF", meaning: "Enclosure size correction factor" }, { symbol: "AFB", meaning: "Arc-flash boundary", unit: "mm" }], "IEEE 1584 predicts thermal incident energy and boundary; it does not select PPE or authorize energized work."),
  "lighting-calculator": make("Lighting calculation equations", "The lumen method estimates average maintained illuminance from room area, fixture output, utilization, and maintenance conditions.", ["Φrequired = E × A / (UF × MF)", "N = ceil(Φrequired / Φfixture)", "Einstalled = N × Φfixture × UF × MF / A", "I = N × Pfixture / (V × pf)"], [{ symbol: "Φrequired", meaning: "Fixture lumens required before utilization and maintenance losses", unit: "lm" }, { symbol: "E", meaning: "Target or achieved maintained illuminance", unit: "lx" }, { symbol: "A", meaning: "Illuminated area", unit: "m²" }, { symbol: "UF", meaning: "Utilization factor" }, { symbol: "MF", meaning: "Maintenance factor" }, { symbol: "N", meaning: "Whole number of fixtures" }, { symbol: "Φfixture", meaning: "Rated luminous flux per fixture", unit: "lm" }, { symbol: "Pfixture", meaning: "Input power per fixture", unit: "W" }, { symbol: "I", meaning: "Steady-state lighting current", unit: "A" }], "A lumen-method result does not prove uniformity, glare control, emergency-lighting compliance, or LED-driver inrush compatibility."),
  "cable-tray-fill-calculator": make("Cable tray fill equations", "Cable outside diameter determines occupied area. Some arrangements instead require a side-by-side width check.", ["Acable = π × OD² / 4", "Acables = Σ(n × Acable)", "Area fill = Acables / (W × D) × 100", "Single-layer width = Σ(n × OD)"], [{ symbol: "Acable", meaning: "Cross-sectional area based on cable outside diameter", unit: "mm²" }, { symbol: "OD", meaning: "Finished cable outside diameter", unit: "mm" }, { symbol: "n", meaning: "Quantity of one cable group" }, { symbol: "W", meaning: "Clear usable tray width", unit: "mm" }, { symbol: "D", meaning: "Clear usable cable depth", unit: "mm" }], "The mathematical fill must be evaluated using the rule applicable to the cable type, voltage, tray, arrangement, and adopted code edition."),
  "stationary-battery-sizing-calculator": make("Stationary battery screening equations", "The calculator first integrates DC ampere-hours, then applies explicit efficiency, usable-capacity, temperature, aging, and design factors.", ["Ahbase = Σ(Ii × ti)", "Ahrequired = Ahbase × Faging × Fmargin / (η × Fusable × Ftemperature)", "Nseries = max(ceil(Vnom/Vcell), ceil(Vmin/VEODV))", "Nparallel = ceil(Ahrequired/Ahcandidate)", "Icharger ≈ Icontinuous + Ahrequired/trecharge"], [{ symbol: "Ahbase", meaning: "Integrated uncorrected duty-cycle capacity", unit: "Ah" }, { symbol: "Ii", meaning: "DC load current during period i", unit: "A" }, { symbol: "ti", meaning: "Duration of period i", unit: "h" }, { symbol: "η", meaning: "DC conversion and distribution efficiency" }, { symbol: "Fusable", meaning: "Usable-capacity fraction" }, { symbol: "Ftemperature", meaning: "Capacity factor at minimum battery temperature" }, { symbol: "VEODV", meaning: "End-of-discharge voltage per cell", unit: "V" }], "This energy-integration screen does not replace manufacturer discharge tables or the limiting-period cell selection required for a complete stationary battery design."),
  "residential-electrical-load-calculator": make("Residential demand and service-current equations", "Connected load and calculated demand are different. The selected workflow applies either an NEC optional-method screen or explicit user-entered planning factors.", ["NEC screen: Dgeneral = first 10,000 VA + 40% × remainder", "Dtotal = Dgeneral + max(HVACcool, HVACheat) + DEVSE", "Planning: Dtotal = Σ(Pcategory × Fcategory) + max(HVAC) + DEVSE", "Iservice = Dtotal / Vservice"], [{ symbol: "D", meaning: "Calculated dwelling demand", unit: "VA" }, { symbol: "Fcategory", meaning: "User-entered category demand factor" }, { symbol: "HVAC", meaning: "Applicable noncoincident heating or cooling contribution", unit: "VA" }, { symbol: "DEVSE", meaning: "EV charging service contribution after entered factor", unit: "VA" }, { symbol: "Iservice", meaning: "Calculated service current", unit: "A" }], "The result is a screening value; the adopted code, utility, authority worksheet, service conductors, and listed equipment govern final approval."),
  "nema-ip-rating-converter": make("NEMA and IEC IP cross-reference method", "An IEC IP code has separate solid-object/access and water digits. NEMA Type requirements include additional environmental and construction characteristics, so the relationship is not reversible equivalence.", ["IP code = IPXY", "X = access and solid foreign-object protection (0 to 6)", "Y = water-ingress protection (0 to 9)", "NEMA Type → IP meet-or-exceed reference", "IP rating ↛ equivalent NEMA Type"], [{ symbol: "X", meaning: "IEC IP first characteristic numeral for access and solid objects" }, { symbol: "Y", meaning: "IEC IP second characteristic numeral for water" }, { symbol: "NEMA Type", meaning: "Enclosure environmental and construction classification under NEMA 250" }], "Select and verify the complete enclosure assembly under the standard and certification required by the installation; a lookup result cannot transfer certification between systems.")
};
