export const toolIcons: Record<string, string> = {
  "spd-calculator": "SPD",
  "voltage-drop-calculator": "Vd",
  "cable-size-calculator": "mm²",
  "conduit-fill-calculator": "%",
  "dc-voltage-drop-calculator": "DC",
  "awg-wire-size-calculator": "AWG",
  "mm2-to-awg-converter": "↔",
  "circuit-breaker-size-calculator": "A",
  "transformer-sizing-calculator": "kVA",
  "short-circuit-current-calculator": "kA",
  "kw-kva-amp-calculator": "kW",
  "three-phase-current-calculator": "3P",
  "motor-current-calculator": "M",
  "ev-charger-load-calculator": "EV",
  "cable-gland-size-calculator": "M",
  "busbar-current-rating-calculator": "Cu",
  "fuse-sizing-calculator": "F",
  "power-factor-correction-calculator": "PF",
  "motor-starter-selection-calculator": "YΔ",
  "three-phase-voltage-unbalance-calculator": "3V",
  "pv-combiner-box-sizing-calculator": "PV",
  "advanced-spd-selection-calculator": "Up",
  "mcb-inrush-compatibility-checker": "C",
  "rcd-rcbo-selector": "ΔI",
  "ats-selection-calculator": "ATS",
  "cable-lug-selector": "LUG",
  "battery-c-rate-runtime-calculator": "C",
  "energy-cost-calculator": "kWh",
  "terminal-heating-calculator": "I²R",
  "busbar-short-circuit-force-calculator": "F",
  "ohms-law-calculator": "Ω",
  "watts-amps-volts-calculator": "W/A",
  "ev-charging-time-cost-calculator": "EV",
  "battery-charging-time-calculator": "h",
  "resistor-series-parallel-calculator": "R",
  "electrical-unit-converter": "↔",
  "contactor-selection-calculator": "AC3",
  "breaker-selectivity-calculator": "Σ",
  "lightning-risk-assessment-calculator": "LPS",
  "enclosure-temperature-rise-calculator": "ΔT",
  "panel-heat-loss-calculator": "ΣW",
  "pv-string-sizing-calculator": "PV",
  "off-grid-solar-system-calculator": "PV+",
  "spd-backup-fuse-calculator": "SPD/F",
  "earth-fault-loop-impedance-calculator": "Zs",
  "cable-derating-factor-calculator": "K",
  "maximum-demand-calculator": "MD",
  "protective-conductor-size-calculator": "PE",
  "cable-short-circuit-thermal-calculator": "I²t",
  "motor-starting-voltage-drop-calculator": "ΔV",
  "vfd-sizing-protection-calculator": "VFD",
  "arc-flash-incident-energy-calculator": "AF",
  "solid-state-relay-calculator": "SSR",
  "afdd-selection-calculator": "AFDD",
  "dc-breaker-sizing-calculator": "DC",
  "pv-dc-isolator-sizing-calculator": "PV",
  "acb-lsig-setting-calculator": "LSIG",
  "ct-ratio-burden-calculator": "CT",
  "breaker-accessory-power-calculator": "VA",
  "pv-dc-ats-calculator": "DC/ATS"
};

export function toolIcon(slug: string) {
  return toolIcons[slug] ?? "V";
}
